#ifndef CUGUGA_GPU_GUGA_CUDA_KERNELS_API_H
#define CUGUGA_GPU_GUGA_CUDA_KERNELS_API_H

#include <cuda_runtime.h>

#include <cstdint>

extern "C" void guga_epq_contribs_one_debug_launch(
    const int32_t* child,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    int norb,
    int csf_idx,
    const int8_t* steps,
    const int32_t* nodes,
    int p,
    int q,
    int max_out,
    int32_t* out_idx,
    double* out_coeff,
    int* out_count,
    int* out_overflow);

extern "C" void guga_epq_apply_g_debug_launch(
    const int32_t* child,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    int norb,
    int csf_idx,
    const int8_t* steps,
    const int32_t* nodes,
    const double* g_flat,
    double thresh_gpq,
    double thresh_contrib,
    int max_out,
    int32_t* out_idx,
    double* out_val,
    int* out_count,
    int* out_overflow,
    int* out_n_pairs);

extern "C" void guga_epq_contribs_many_count_launch(
    const int32_t* child,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    const int8_t* steps_table,
    const int32_t* nodes_table,
    int ncsf,
    int norb,
    const int32_t* task_csf,
    const int32_t* task_p,
    const int32_t* task_q,
    int ntasks,
    int32_t* counts,
    int* overflow_flag,
    int threads);

extern "C" void guga_epq_contribs_many_count_launch_stream(
    const int32_t* child,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    const int8_t* steps_table,
    const int32_t* nodes_table,
    int ncsf,
    int norb,
    const int32_t* task_csf,
    const int32_t* task_p,
    const int32_t* task_q,
    int ntasks,
    int32_t* counts,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" void guga_epq_contribs_many_write_launch(
    const int32_t* child,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    const int8_t* steps_table,
    const int32_t* nodes_table,
    int ncsf,
    int norb,
    const int32_t* task_csf,
    const int32_t* task_p,
    const int32_t* task_q,
    int ntasks,
    const int64_t* offsets,
    int32_t* out_idx,
    double* out_coeff,
    int32_t* out_task_csf,
    int32_t* out_task_pq,
    int* overflow_flag,
    int threads);

extern "C" void guga_epq_contribs_many_write_launch_stream(
    const int32_t* child,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    const int8_t* steps_table,
    const int32_t* nodes_table,
    int ncsf,
    int norb,
    const int32_t* task_csf,
    const int32_t* task_p,
    const int32_t* task_q,
    int ntasks,
    const int64_t* offsets,
    int32_t* out_idx,
    double* out_coeff,
    int32_t* out_task_csf,
    int32_t* out_task_pq,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" void guga_epq_contribs_many_count_allpairs_launch_stream(
    const int32_t* child,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    const int8_t* steps_table,
    const int32_t* nodes_table,
    int ncsf,
    int norb,
    int j_start,
    int j_count,
    int32_t* counts,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" void guga_epq_contribs_many_write_allpairs_launch_stream(
    const int32_t* child,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    const int8_t* steps_table,
    const int32_t* nodes_table,
    int ncsf,
    int norb,
    int j_start,
    int j_count,
    const int64_t* offsets,
    int32_t* out_idx,
    void* out_coeff,
    int out_coeff_type,
    int32_t* out_task_csf,
    void* out_task_pq,
    int out_task_pq_type,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" void guga_epq_contribs_many_fused_allpairs_launch_stream(
    const int32_t* child,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    const int8_t* steps_table,
    const int32_t* nodes_table,
    int ncsf,
    int norb,
    int j_start,
    int j_count,
    int max_out,
    int32_t* out_idx,
    void* out_coeff,
    int out_coeff_type,
    int32_t* out_task_csf,
    void* out_task_pq,
    int out_task_pq_type,
    int* nnz_counter,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" void guga_epq_contribs_many_count_allpairs_recompute_launch_stream(
    const int32_t* child,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    int ncsf,
    int norb,
    int j_start,
    int j_count,
    int32_t* counts,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" void guga_epq_contribs_many_write_allpairs_recompute_launch_stream(
    const int32_t* child,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    int ncsf,
    int norb,
    int j_start,
    int j_count,
    const int64_t* offsets,
    int32_t* out_idx,
    void* out_coeff,
    int out_coeff_type,
    int32_t* out_task_csf,
    void* out_task_pq,
    int out_task_pq_type,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" void guga_epq_contribs_many_count_allpairs_recompute_warp_launch_stream(
    const int32_t* child,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    int ncsf,
    int norb,
    int j_start,
    int j_count,
    int32_t* counts,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" void guga_epq_contribs_many_write_allpairs_recompute_warp_launch_stream(
    const int32_t* child,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    int ncsf,
    int norb,
    int j_start,
    int j_count,
    const int64_t* offsets,
    int32_t* out_idx,
    void* out_coeff,
    int out_coeff_type,
    int32_t* out_task_csf,
    void* out_task_pq,
    int out_task_pq_type,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t guga_qmc_spawn_one_body_launch_stream(
    const int32_t* child,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    const int8_t* steps_table,
    const int32_t* nodes_table,
    int ncsf,
    int norb,
    const int32_t* x_idx,
    const double* x_val,
    int m,
    const double* h_eff_flat,
    double eps,
    int nspawn,
    uint64_t seed,
    double initiator_t,
    int32_t* out_idx,
    double* out_val,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t guga_qmc_spawn_hamiltonian_launch_stream(
    const int32_t* child,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    const int8_t* steps_table,
    const int32_t* nodes_table,
    int ncsf,
    int norb,
    const int32_t* x_idx,
    const double* x_val,
    int m,
    const double* h_base_flat,
    const double* eri_mat,
    double eps,
    int nspawn_one,
    int nspawn_two,
    uint64_t seed,
    double initiator_t,
    int32_t* out_idx,
    double* out_val,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t guga_qmc_spawn_hamiltonian_u64_f64_launch_stream(
    const int32_t* child,
    const int16_t* node_twos,
    int norb,
    const uint64_t* x_key,
    const double* x_val,
    int m,
    const double* h_base_flat,
    const double* eri_mat,
    const float* pair_alias_prob,
    const int32_t* pair_alias_idx,
    const double* pair_norm,
    double pair_norm_sum,
    int pair_sampling_mode,
    double eps,
    int nspawn_one,
    int nspawn_two,
    uint64_t seed,
    double initiator_t,
    uint64_t* out_key,
    double* out_val,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t guga_qmc_coalesce_coo_i32_f64_launch_stream(
    const int32_t* idx_in,
    const double* val_in,
    int n,
    int32_t* idx_out,
    double* val_out,
    int* out_nnz,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t guga_qmc_phi_pivot_resample_i32_f64_launch_stream(
    const int32_t* idx_in,
    const double* val_in,
    int n_in,
    int32_t* idx_out,
    double* val_out,
    int* out_nnz,
    int m,
    int pivot,
    uint64_t seed,
    cudaStream_t stream,
    int threads);

extern "C" void* guga_qmc_workspace_create(int max_n, int max_m);

extern "C" void guga_qmc_workspace_destroy(void* ws_handle);

extern "C" cudaError_t guga_qmc_coalesce_coo_i32_f64_ws_launch_stream(
    void* ws_handle,
    const int32_t* idx_in,
    const double* val_in,
    int n,
    int32_t* idx_out,
    double* val_out,
    int* out_nnz,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t guga_qmc_phi_pivot_resample_i32_f64_ws_launch_stream(
    void* ws_handle,
    const int32_t* idx_in,
    const double* val_in,
    int n_in,
    int32_t* idx_out,
    double* val_out,
    int* out_nnz,
    int m,
    int pivot,
    uint64_t seed,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t guga_counts_to_offsets_exclusive_scan_launch(
    const int32_t* counts,
    int ntasks,
    int64_t* offsets,
    int64_t* total_host);

extern "C" cudaError_t guga_counts_to_offsets_exclusive_scan_launch_stream(
    const int32_t* counts,
    int ntasks,
    int64_t* offsets,
    int64_t* total_host,
    cudaStream_t stream);

extern "C" cudaError_t guga_ell_spmv_f64_launch_stream(
    const int32_t* col_idx,
    const double* val,
    int nrows,
    int width,
    const double* x,
    double* y,
    int add,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t guga_ell_spmm_f64_launch_stream(
    const int32_t* col_idx,
    const double* val,
    int nrows,
    int width,
    const double* x,
    int ldx,
    double* y,
    int ldy,
    int nvec,
    int add,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t guga_sell_spmv_f64_launch_stream(
    const int64_t* slice_ptr,
    const int32_t* slice_width,
    const int32_t* col_idx,
    const double* val,
    int nrows,
    int slice_height,
    const double* x,
    double* y,
    int add,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t guga_sell_spmm_f64_launch_stream(
    const int64_t* slice_ptr,
    const int32_t* slice_width,
    const int32_t* col_idx,
    const double* val,
    int nrows,
    int slice_height,
    const double* x,
    int ldx,
    double* y,
    int ldy,
    int nvec,
    int add,
    cudaStream_t stream,
    int threads);

extern "C" void guga_epq_apply_gather_inplace_launch_stream(
    const int32_t* child,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    const int8_t* steps_table,
    const int32_t* nodes_table,
    int ncsf,
    int norb,
    int p,
    int q,
    const double* x,
    int nvec,
    double alpha,
    double* y,
    int add,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" void launch_scatter_embed(
    const double* x_sub,
    const int64_t* sub_to_full,
    double* x_full,
    int nsub,
    int threads,
    cudaStream_t stream);

extern "C" void launch_gather_project(
    const double* y_full,
    const int64_t* sub_to_full,
    double* y_sub,
    int nsub,
    int threads,
    cudaStream_t stream);

extern "C" void guga_epq_apply_weighted_many_atomic_launch(
    const int32_t* child,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    const int8_t* steps_table,
    const int32_t* nodes_table,
    int ncsf,
    int norb,
    const int32_t* task_csf,
    const int32_t* task_p,
    const int32_t* task_q,
    const double* task_wgt,
    const double* task_scale,
    int ntasks,
    double* y,
    int* overflow_flag,
    int threads);

extern "C" void guga_apply_g_flat_scatter_atomic_launch(
    const int32_t* child,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    const int8_t* steps_table,
    const int32_t* nodes_table,
    int ncsf,
    int norb,
    const int32_t* task_csf,
    const double* task_scale,
    const double* task_g,
    int64_t g_stride,
    int ntasks,
    double* y,
    int* overflow_flag,
    int threads);

extern "C" void guga_apply_g_flat_task_sums_launch(
    const int32_t* child,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    const int8_t* steps_table,
    const int32_t* nodes_table,
    int ncsf,
    int norb,
    const int32_t* task_csf,
    const double* task_scale,
    const double* task_g,
    int64_t g_stride,
    int ntasks,
    double* out_sum,
    int* overflow_flag,
    int threads);

extern "C" void guga_apply_g_flat_scatter_atomic_launch_stream(
    const int32_t* child,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    const int8_t* steps_table,
    const int32_t* nodes_table,
    int ncsf,
    int norb,
    const int32_t* task_csf,
    const double* task_scale,
    const double* task_g,
    int64_t g_stride,
    int ntasks,
    double* y,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" void guga_apply_g_flat_scatter_atomic_f32_launch(
    const int32_t* child,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    const int8_t* steps_table,
    const int32_t* nodes_table,
    int ncsf,
    int norb,
    const int32_t* task_csf,
    const float* task_scale,
    const float* task_g,
    int64_t g_stride,
    int ntasks,
    float* y,
    int* overflow_flag,
    int threads);

extern "C" void guga_apply_g_flat_scatter_atomic_f32_launch_stream(
    const int32_t* child,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    const int8_t* steps_table,
    const int32_t* nodes_table,
    int ncsf,
    int norb,
    const int32_t* task_csf,
    const float* task_scale,
    const float* task_g,
    int64_t g_stride,
    int ntasks,
    float* y,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" void guga_apply_g_flat_scatter_atomic_epq_table_launch_stream(
    const int8_t* steps_table,
    int ncsf,
    int norb,
    const void* epq_indptr,
    int epq_indptr_type,
    const int32_t* epq_indices,
    const void* epq_pq,
    int epq_pq_type,
    const double* epq_data,
    const int32_t* task_csf,
    const double* task_scale,
    const double* task_g,
    int64_t g_stride,
    int ntasks,
    double* y,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" void guga_apply_g_flat_gather_epq_table_launch_stream(
    const int8_t* steps_table,
    int ncsf,
    int norb,
    const void* epq_t_indptr,
    int epq_t_indptr_type,
    const int32_t* epq_t_source,
    const void* epq_t_pq,
    int epq_t_pq_type,
    const double* epq_t_data,
    const int32_t* task_row_by_csf,
    const double* task_scale_by_csf,
    const double* task_g,
    int64_t g_stride,
    double* y,
    int* overflow_flag,
    cudaStream_t stream,
    int threads,
    int add);

extern "C" void guga_apply_g_flat_gather_epq_table_mixed_launch_stream(
    const int8_t* steps_table,
    int ncsf,
    int norb,
    const void* epq_t_indptr,
    int epq_t_indptr_type,
    const int32_t* epq_t_source,
    const void* epq_t_pq,
    int epq_t_pq_type,
    const float* epq_t_data,
    const int32_t* task_row_by_csf,
    const double* task_scale_by_csf,
    const double* task_g,
    int64_t g_stride,
    double* y,
    int* overflow_flag,
    cudaStream_t stream,
    int threads,
    int add);

extern "C" void guga_apply_g_flat_scatter_atomic_epq_table_f32_launch_stream(
    const int8_t* steps_table,
    int ncsf,
    int norb,
    const void* epq_indptr,
    int epq_indptr_type,
    const int32_t* epq_indices,
    const void* epq_pq,
    int epq_pq_type,
    const float* epq_data,
    const int32_t* task_csf,
    const float* task_scale,
    const float* task_g,
    int64_t g_stride,
    int ntasks,
    float* y,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" void guga_apply_g_flat_scatter_atomic_epq_table_mixed_launch_stream(
    const int8_t* steps_table,
    int ncsf,
    int norb,
    const void* epq_indptr,
    int epq_indptr_type,
    const int32_t* epq_indices,
    const void* epq_pq,
    int epq_pq_type,
    const float* epq_data,
    const int32_t* task_csf,
    const double* task_scale,
    const double* task_g,
    int64_t g_stride,
    int ntasks,
    double* y,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" void guga_apply_g_flat_scatter_atomic_epq_table_tile_launch_stream(
    const int8_t* steps_table,
    int ncsf,
    int norb,
    const int64_t* local_indptr,
    const int32_t* epq_indices,
    const void* epq_pq,
    int epq_pq_type,
    const double* epq_data,
    const double* task_g,
    int64_t g_stride,
    const double* task_scale,
    int j_start,
    int j_count,
    double* y,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" void guga_apply_g_flat_scatter_atomic_epq_table_tile_f32_launch_stream(
    const int8_t* steps_table,
    int ncsf,
    int norb,
    const int64_t* local_indptr,
    const int32_t* epq_indices,
    const void* epq_pq,
    int epq_pq_type,
    const float* epq_data,
    const float* task_g,
    int64_t g_stride,
    const float* task_scale,
    int j_start,
    int j_count,
    float* y,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" void guga_apply_g_flat_scatter_atomic_epq_table_tile_f32_kahan_launch_stream(
    const int8_t* steps_table,
    int ncsf,
    int norb,
    const int64_t* local_indptr,
    const int32_t* epq_indices,
    const void* epq_pq,
    int epq_pq_type,
    const float* epq_data,
    const float* task_g,
    int64_t g_stride,
    const float* task_scale,
    int j_start,
    int j_count,
    float* y,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" void guga_apply_g_flat_scatter_atomic_epq_table_tile_mixed_launch_stream(
    const int8_t* steps_table,
    int ncsf,
    int norb,
    const int64_t* local_indptr,
    const int32_t* epq_indices,
    const void* epq_pq,
    int epq_pq_type,
    const float* epq_data,
    const double* task_g,
    int64_t g_stride,
    const double* task_scale,
    int j_start,
    int j_count,
    double* y,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" void guga_apply_g_flat_gather_epq_table_f32_launch_stream(
    const int8_t* steps_table,
    int ncsf,
    int norb,
    const void* epq_t_indptr,
    int epq_t_indptr_type,
    const int32_t* epq_t_source,
    const void* epq_t_pq,
    int epq_t_pq_type,
    const float* epq_t_data,
    const int32_t* task_row_by_csf,
    const float* task_scale_by_csf,
    const float* task_g,
    int64_t g_stride,
    float* y,
    int* overflow_flag,
    cudaStream_t stream,
    int threads,
    int add);

extern "C" void guga_apply_csr_eri_mat_fused_epq_table_range_launch_stream(
    const int8_t* steps_table,
    int ncsf,
    int norb,
    const int64_t* epq_indptr,
    const int32_t* epq_indices,
    const void* epq_pq,
    int epq_pq_type,
    const double* epq_data,
    const int32_t* row_j,
    const int32_t* row_k,
    const int64_t* csr_indptr,
    const int32_t* csr_indices,
    const double* csr_data,
    int row_start,
    int nrows,
    const double* eri_mat_t,
    int nops,
    double half,
    const double* x,
    double* y,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" void guga_apply_csr_eri_mat_fused_epq_table_range_f64_out_f32_coeff_launch_stream(
    const int8_t* steps_table,
    int ncsf,
    int norb,
    const int64_t* epq_indptr,
    const int32_t* epq_indices,
    const void* epq_pq,
    int epq_pq_type,
    const float* epq_data,
    const int32_t* row_j,
    const int32_t* row_k,
    const int64_t* csr_indptr,
    const int32_t* csr_indices,
    const double* csr_data,
    int row_start,
    int nrows,
    const double* eri_mat_t,
    int nops,
    double half,
    const double* x,
    double* y,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" void guga_apply_csr_eri_mat_fused_epq_table_range_f32_launch_stream(
    const int8_t* steps_table,
    int ncsf,
    int norb,
    const int64_t* epq_indptr,
    const int32_t* epq_indices,
    const void* epq_pq,
    int epq_pq_type,
    const float* epq_data,
    const int32_t* row_j,
    const int32_t* row_k,
    const int64_t* csr_indptr,
    const int32_t* csr_indices,
    const float* csr_data,
    int row_start,
    int nrows,
    const float* eri_mat_t,
    int nops,
    float half,
    const float* x,
    float* y,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

// Kahan-compensated FP32 gather kernel (Neumaier compensated summation).
extern "C" void guga_apply_g_flat_gather_epq_table_f32_kahan_launch_stream(
    const int8_t* steps_table,
    int ncsf,
    int norb,
    const void* epq_t_indptr,
    int epq_t_indptr_type,
    const int32_t* epq_t_source,
    const void* epq_t_pq,
    int epq_t_pq_type,
    const float* epq_t_data,
    const int32_t* task_row_by_csf,
    const float* task_scale_by_csf,
    const float* task_g,
    int64_t g_stride,
    float* y,
    int* overflow_flag,
    cudaStream_t stream,
    int threads,
    int add);

extern "C" void guga_apply_g_flat_gather_epq_transpose_range_launch_stream(
    const int8_t* steps_table,
    int ncsf,
    int norb,
    const void* epq_t_indptr,
    int epq_t_indptr_type,
    const int32_t* epq_t_source,
    const void* epq_t_pq,
    int epq_t_pq_type,
    const double* epq_t_data,
    const double* g_block,
    int64_t g_stride,
    int k_start,
    int k_count,
    double* y,
    int* overflow_flag,
    cudaStream_t stream,
    int threads,
    int add);

extern "C" void guga_apply_g_flat_gather_epq_transpose_range_mixed_launch_stream(
    const int8_t* steps_table,
    int ncsf,
    int norb,
    const void* epq_t_indptr,
    int epq_t_indptr_type,
    const int32_t* epq_t_source,
    const void* epq_t_pq,
    int epq_t_pq_type,
    const float* epq_t_data,
    const double* g_block,
    int64_t g_stride,
    int k_start,
    int k_count,
    double* y,
    int* overflow_flag,
    cudaStream_t stream,
    int threads,
    int add);

extern "C" void guga_apply_g_flat_gather_epq_transpose_range_f32_launch_stream(
    const int8_t* steps_table,
    int ncsf,
    int norb,
    const void* epq_t_indptr,
    int epq_t_indptr_type,
    const int32_t* epq_t_source,
    const void* epq_t_pq,
    int epq_t_pq_type,
    const float* epq_t_data,
    const float* g_block,
    int64_t g_stride,
    int k_start,
    int k_count,
    float* y,
    int* overflow_flag,
    cudaStream_t stream,
    int threads,
    int add);

extern "C" void guga_apply_g_flat_gather_epq_transpose_range_f32_kahan_launch_stream(
    const int8_t* steps_table,
    int ncsf,
    int norb,
    const void* epq_t_indptr,
    int epq_t_indptr_type,
    const int32_t* epq_t_source,
    const void* epq_t_pq,
    int epq_t_pq_type,
    const float* epq_t_data,
    const float* g_block,
    int64_t g_stride,
    int k_start,
    int k_count,
    float* y,
    int* overflow_flag,
    cudaStream_t stream,
    int threads,
    int add);

// Kahan-compensated FP32 fused CSR+EPQ kernel.
extern "C" void guga_apply_csr_eri_mat_fused_epq_table_range_f32_kahan_launch_stream(
    const int8_t* steps_table,
    int ncsf,
    int norb,
    const int64_t* epq_indptr,
    const int32_t* epq_indices,
    const void* epq_pq,
    int epq_pq_type,
    const float* epq_data,
    const int32_t* row_j,
    const int32_t* row_k,
    const int64_t* csr_indptr,
    const int32_t* csr_indices,
    const float* csr_data,
    int row_start,
    int nrows,
    const float* eri_mat_t,
    int nops,
    float half,
    const float* x,
    float* y,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" void guga_build_w_from_csr_unitnnz_launch_stream(
    const int32_t* row_j,
    const int32_t* row_k,
    const int32_t* csr_rs,
    const double* csr_c,
    int nrows,
    const double* x,
    int ncsf,
    int nops,
    double* w_out,
    int64_t w_stride,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" void guga_build_w_from_epq_table_launch_stream(
    const void* epq_indptr,
    int epq_indptr_type,
    const int32_t* epq_indices,
    const void* epq_pq,
    int epq_pq_type,
    const double* epq_data,
    const double* x,
    int ncsf,
    int nops,
    double* w_out,
    int64_t w_stride,
    int* overflow_flag,
    cudaStream_t stream,
    int threads,
    int k_start,
    int k_count);

extern "C" void guga_build_w_from_epq_transpose_range_launch_stream(
    const void* epq_t_indptr,
    int epq_t_indptr_type,
    const int32_t* epq_t_source,
    const void* epq_t_pq,
    int epq_t_pq_type,
    const double* epq_t_data,
    const double* x,
    int ncsf,
    int nops,
    double* w_out,
    int64_t w_stride,
    int* overflow_flag,
    cudaStream_t stream,
    int threads,
    int k_start,
    int k_count);

extern "C" void guga_build_w_from_epq_transpose_range_f64_out_f32_coeff_launch_stream(
    const void* epq_t_indptr,
    int epq_t_indptr_type,
    const int32_t* epq_t_source,
    const void* epq_t_pq,
    int epq_t_pq_type,
    const float* epq_t_data,
    const double* x,
    int ncsf,
    int nops,
    double* w_out,
    int64_t w_stride,
    int* overflow_flag,
    cudaStream_t stream,
    int threads,
    int k_start,
    int k_count);

extern "C" void guga_build_w_from_epq_table_f32_launch_stream(
    const void* epq_indptr,
    int epq_indptr_type,
    const int32_t* epq_indices,
    const void* epq_pq,
    int epq_pq_type,
    const float* epq_data,
    const float* x,
    int ncsf,
    int nops,
    float* w_out,
    int64_t w_stride,
    int* overflow_flag,
    cudaStream_t stream,
    int threads,
    int k_start,
    int k_count);

extern "C" void guga_build_w_from_epq_table_f64_out_f32_coeff_launch_stream(
    const void* epq_indptr,
    int epq_indptr_type,
    const int32_t* epq_indices,
    const void* epq_pq,
    int epq_pq_type,
    const float* epq_data,
    const double* x,
    int ncsf,
    int nops,
    double* w_out,
    int64_t w_stride,
    int* overflow_flag,
    cudaStream_t stream,
    int threads,
    int k_start,
    int k_count);

extern "C" void guga_build_w_from_epq_transpose_range_f32_launch_stream(
    const void* epq_t_indptr,
    int epq_t_indptr_type,
    const int32_t* epq_t_source,
    const void* epq_t_pq,
    int epq_t_pq_type,
    const float* epq_t_data,
    const float* x,
    int ncsf,
    int nops,
    float* w_out,
    int64_t w_stride,
    int* overflow_flag,
    cudaStream_t stream,
    int threads,
    int k_start,
    int k_count);

extern "C" void guga_build_t_from_epq_table_launch_stream(
    const int8_t* steps_table,
    const int64_t* epq_indptr,
    const int32_t* epq_indices,
    const void* epq_pq,
    int epq_pq_type,
    const double* epq_data,
    const double* c_vec,
    int ncsf,
    int norb,
    int nops,
    double* t_out,
    int64_t t_stride,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" void guga_build_t_from_epq_table_f32_launch_stream(
    const int8_t* steps_table,
    const int64_t* epq_indptr,
    const int32_t* epq_indices,
    const void* epq_pq,
    int epq_pq_type,
    const float* epq_data,
    const float* c_vec,
    int ncsf,
    int norb,
    int nops,
    float* t_out,
    int64_t t_stride,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" void guga_apply_g_flat_task_sums_launch_stream(
    const int32_t* child,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    const int8_t* steps_table,
    const int32_t* nodes_table,
    int ncsf,
    int norb,
    const int32_t* task_csf,
    const double* task_scale,
    const double* task_g,
    int64_t g_stride,
    int ntasks,
    double* out_sum,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t guga_build_w_diag_from_steps_launch_stream(
    const int8_t* steps_table,
    int ncsf,
    int norb,
    int j_start,
    int j_count,
    const double* x,
    int nops,
    double* w_out,
    int64_t w_stride,
    cudaStream_t stream,
    int threads,
    int relative_w);

extern "C" cudaError_t guga_build_w_diag_from_steps_f32_launch_stream(
    const int8_t* steps_table,
    int ncsf,
    int norb,
    int j_start,
    int j_count,
    const float* x,
    int nops,
    float* w_out,
    int64_t w_stride,
    cudaStream_t stream,
    int threads,
    int relative_w);

extern "C" cudaError_t guga_build_occ_block_from_steps_launch_stream(
    const int8_t* steps_table,
    int ncsf,
    int norb,
    int j_start,
    int j_count,
    double* occ_out,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t guga_build_hdiag_det_guess_from_steps_launch_stream(
    const int8_t* steps_table,
    int ncsf,
    int norb,
    int neleca_det,
    const double* h1e_diag,
    const double* eri_ppqq,
    const double* eri_pqqp,
    double* hdiag_out,
    cudaStream_t stream,
    int threads);

extern "C" void guga_build_t_block_epq_atomic_launch(
    const int32_t* child,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    const int8_t* steps_table,
    const int32_t* nodes_table,
    int ncsf,
    int norb,
    const double* c,
    const int32_t* p_list,
    const int32_t* q_list,
    int nops_block,
    double* out,
    int64_t out_stride,
    int* overflow_flag,
    int threads);

extern "C" void guga_build_t_block_epq_atomic_launch_stream(
    const int32_t* child,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    const int8_t* steps_table,
    const int32_t* nodes_table,
    int ncsf,
    int norb,
    const double* c,
    const int32_t* p_list,
    const int32_t* q_list,
    int nops_block,
    double* out,
    int64_t out_stride,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t guga_kernel25_build_csr_launch(
    const int32_t* j,
    const int32_t* k,
    const int32_t* rs,
    const double* c,
    int nnz_in,
    int coalesce,
    uint64_t* out_row_jk,
    int64_t* out_indptr,
    int32_t* out_indices,
    double* out_data,
    int* out_nrows,
    int* out_nnz);

extern "C" cudaError_t guga_kernel25_build_csr_launch_stream(
    const int32_t* j,
    const int32_t* k,
    const int32_t* rs,
    const double* c,
    int nnz_in,
    int coalesce,
    uint64_t* out_row_jk,
    int64_t* out_indptr,
    int32_t* out_indices,
    double* out_data,
    int* out_nrows,
    int* out_nnz,
    cudaStream_t stream);

extern "C" cudaError_t guga_init_segment_lut();

extern "C" cudaError_t guga_build_g_from_csr_eri_mat_launch(
    const int64_t* indptr,
    const int32_t* indices,
    const double* data,
    int nrows,
    const double* eri_mat,
    int nops,
    double half,
    double* g_out,
    int threads);

extern "C" cudaError_t guga_build_g_from_csr_eri_mat_launch_stream(
    const int64_t* indptr,
    const int32_t* indices,
    const double* data,
    int nrows,
    const double* eri_mat,
    int nops,
    double half,
    double* g_out,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t guga_build_g_from_csr_eri_mat_f64_launch_stream(
    const int64_t* indptr,
    const int32_t* indices,
    const double* data,
    int nrows,
    const double* eri_mat,
    int nops,
    double half,
    double* g_out,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t guga_build_g_from_csr_eri_mat_f32_launch_stream(
    const int64_t* indptr,
    const int32_t* indices,
    const float* data,
    int nrows,
    const float* eri_mat,
    int nops,
    float half,
    float* g_out,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t guga_build_g_from_csr_eri_mat_range_launch_stream(
    const int64_t* indptr,
    const int32_t* indices,
    const double* data,
    int row_start,
    int nrows,
    const double* eri_mat,
    int nops,
    double half,
    double* g_out,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t guga_build_g_from_csr_eri_mat_range_f64_launch_stream(
    const int64_t* indptr,
    const int32_t* indices,
    const double* data,
    int row_start,
    int nrows,
    const double* eri_mat,
    int nops,
    double half,
    double* g_out,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t guga_build_g_from_csr_eri_mat_range_f32_launch_stream(
    const int64_t* indptr,
    const int32_t* indices,
    const float* data,
    int row_start,
    int nrows,
    const float* eri_mat,
    int nops,
    float half,
    float* g_out,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t guga_csr_to_dense_f64_launch_stream(
    const int64_t* indptr,
    const int32_t* indices,
    const double* data,
    int nrows,
    int ncols,
    double* out_dense,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t guga_csr_to_dense_f64_range_launch_stream(
    const int64_t* indptr,
    const int32_t* indices,
    const double* data,
    int row_start,
    int nrows,
    int ncols,
    double* out_dense,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t guga_csr_to_dense_f32_launch_stream(
    const int64_t* indptr,
    const int32_t* indices,
    const float* data,
    int nrows,
    int ncols,
    float* out_dense,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t guga_csr_to_dense_f32_range_launch_stream(
    const int64_t* indptr,
    const int32_t* indices,
    const float* data,
    int row_start,
    int nrows,
    int ncols,
    float* out_dense,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t guga_csr_l_full_to_wt_f64_range_launch_stream(
    const int64_t* indptr,
    const int32_t* indices,
    const double* data,
    int row_start,
    int nrows,
    const double* l_full,
    int naux,
    double* wt_out,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t guga_csr_l_full_to_wt_f32_range_launch_stream(
    const int64_t* indptr,
    const int32_t* indices,
    const float* data,
    int row_start,
    int nrows,
    const float* l_full,
    int naux,
    float* wt_out,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t guga_csr_l_full_to_wt_f32_from_f64_range_launch_stream(
    const int64_t* indptr,
    const int32_t* indices,
    const double* data,
    int row_start,
    int nrows,
    const float* l_full,
    int naux,
    float* wt_out,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t guga_unpack_row_jk_launch_stream(
    const uint64_t* row_jk,
    int nrows,
    int32_t* row_j,
    int32_t* row_k,
    cudaStream_t stream,
    int threads);

typedef struct Kernel25Profile {
  float count_ms;
  float prefix_sum_ms;
  float write_ms;
  float pack_ms;
  float sort_ms;
  float reduce_ms;
  float rle_ms;
  float indptr_ms;
  float unpack_ms;
  float sync_overhead_ms;
  int nnz_in;
  int nnz_out;
  int nrows;
} Kernel25Profile;

extern "C" void* guga_kernel25_workspace_create(int max_tasks, int max_nnz_in);
extern "C" void guga_kernel25_workspace_destroy(void* ws_handle);

extern "C" void guga_kernel25_build_csr_from_jrs_allpairs_deterministic_inplace_device_ws(
    void* ws_handle,
    const int32_t* child,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    const int8_t* steps_table,
    const int32_t* nodes_table,
    int ncsf,
    int norb,
    int j_start,
    int j_count,
    int32_t* out_row_j,
    int32_t* out_row_k,
    int64_t* out_indptr,
    int32_t* out_indices,
    void* out_data,
    int out_data_type,
    int max_out,
    int* overflow_flag,
    cudaStream_t stream,
    int threads,
    int coalesce,
    int* out_nrows_host,
    int* out_nnz_host,
    int* out_nnz_in_host,
    int sync,
    int check_overflow_mode,
    int use_fused_count_write,
    Kernel25Profile* out_profile);

extern "C" void guga_kernel25_build_csr_from_tasks_deterministic_inplace_device_ws(
    void* ws_handle,
    const int32_t* child,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    const int8_t* steps_table,
    const int32_t* nodes_table,
    int ncsf,
    int norb,
    const int32_t* task_csf,
    const int32_t* task_p,
    const int32_t* task_q,
    int ntasks,
    int32_t* out_row_j,
    int32_t* out_row_k,
    int64_t* out_indptr,
    int32_t* out_indices,
    void* out_data,
    int out_data_type,
    int max_out,
    int* overflow_flag,
    cudaStream_t stream,
    int threads,
    int coalesce,
    int* out_nrows_host,
    int* out_nnz_host,
    int* out_nnz_in_host,
    int sync,
    int check_overflow);

// Fused hop kernel: single DFS walk fusing W-build + one-body + ERI contraction
template <int MAX_NORB_T, typename T>
void guga_fused_hop_launch_stream(
    const int32_t* child,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    const int8_t* steps_table,
    const int32_t* nodes_table,
    int ncsf,
    int norb,
    int j_start,
    int j_count,
    const T* x,
    const T* eri_mat,
    const T* h_eff_flat,
    T* y,
    int* overflow_flag,
    cudaStream_t stream);

// Phase-1-only fused hop: W-build + ERI contraction, writes G to g_out.
// Phase 2 scatter is handled externally via the EPQ table scatter kernel.
template <int MAX_NORB_T, typename T>
void guga_fused_hop_phase1_launch_stream(
    const int32_t* child,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    const int8_t* steps_table,
    const int32_t* nodes_table,
    int ncsf,
    int norb,
    int j_start,
    int j_count,
    const T* x,
    const T* eri_mat,
    const T* h_eff_flat,
    T* y,
    T* g_out,
    int* overflow_flag,
    cudaStream_t stream);

// Phase-1 + COO output fused hop: W-build + ERI contraction + COO connectivity.
// Phase 2 scatter is handled by guga_coo_scatter_launch_stream.
template <int MAX_NORB_T, typename T>
void guga_fused_hop_phase1_coo_launch_stream(
    const int32_t* child,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    const int8_t* steps_table,
    const int32_t* nodes_table,
    int ncsf,
    int norb,
    int j_start,
    int j_count,
    const T* x,
    const T* eri_mat,
    const T* h_eff_flat,
    T* y,
    T* g_out,
    int* overflow_flag,
    int* coo_nnz_counter,
    int32_t* coo_j_local,
    int32_t* coo_k,
    int16_t* coo_pq,
    T* coo_w2,
    int max_coo,
    cudaStream_t stream);

// Phase-1 + COO output fused hop (merged DFS variant, WP14):
// Groups pairs by (direction, start) and walks shared DRT prefix once per group.
template <int MAX_NORB_T, typename T>
void guga_fused_hop_phase1_coo_merged_launch_stream(
    const int32_t* child,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    const int8_t* steps_table,
    const int32_t* nodes_table,
    int ncsf,
    int norb,
    int j_start,
    int j_count,
    const T* x,
    const T* eri_mat,
    const T* h_eff_flat,
    T* y,
    T* g_out,
    int* overflow_flag,
    int* coo_nnz_counter,
    int32_t* coo_j_local,
    int32_t* coo_k,
    int16_t* coo_pq,
    T* coo_w2,
    int max_coo,
    cudaStream_t stream);

// COO scatter kernel: reads COO triples and scatters G into y.
template <typename T>
void guga_coo_scatter_launch_stream(
    const int32_t* coo_j_local,
    const int32_t* coo_k,
    const int16_t* coo_pq,
    const T* coo_w2,
    const T* g_tile,
    int nops,
    int nnz,
    T* y,
    cudaStream_t stream);

extern "C" void guga_triplet_apply_contracted_all_m_from_epq_table_launch_stream(
    const int16_t* node_twos,
    const int8_t* steps_table,
    const int32_t* nodes_table,
    int ncsf,
    int norb,
    const int64_t* epq_indptr,
    const int32_t* epq_indices,
    const int32_t* epq_pq,
    const double* x,
    const double* h_re,
    const double* h_im,
    const float* sixj_211,
    const float* t_factor,
    int twos_max,
    double* y_re,
    double* y_im,
    cudaStream_t stream,
    int threads);

extern "C" void guga_triplet_apply_contracted_all_m_dfs_launch_stream(
    const int32_t* child_bra,
    const int16_t* node_twos_bra,
    const int64_t* child_prefix_bra,
    int root_bra,
    int leaf_bra,
    int ncsf_bra,
    int twos_bra_total,
    const int16_t* node_twos_ket,
    const int8_t* steps_table_ket,
    const int32_t* nodes_table_ket,
    int ncsf_ket,
    int norb,
    int twos_ket_total,
    const double* x,
    const double* h_re,
    const double* h_im,
    const float* sixj_211,
    const float* t_factor,
    int twos_max,
    double* y_re,
    double* y_im,
    cudaStream_t stream,
    int threads);

extern "C" void guga_triplet_build_rho_all_m_from_epq_table_launch_stream(
    const int16_t* node_twos,
    const int8_t* steps_table,
    const int32_t* nodes_table,
    int ncsf,
    int norb,
    const int64_t* epq_indptr,
    const int32_t* epq_indices,
    const int32_t* epq_pq,
    const double* c_bra,
    int nb,
    const double* c_ket,
    int nk,
    const double* eta_re,
    const double* eta_im,
    const float* sixj_211,
    const float* t_factor,
    int twos_max,
    double* rho_re,
    double* rho_im,
    cudaStream_t stream,
    int threads);

extern "C" void guga_triplet_build_rho_all_m_dfs_launch_stream(
    const int32_t* child_bra,
    const int16_t* node_twos_bra,
    const int64_t* child_prefix_bra,
    int root_bra,
    int leaf_bra,
    int ncsf_bra,
    int twos_bra_total,
    const int16_t* node_twos_ket,
    const int8_t* steps_table_ket,
    const int32_t* nodes_table_ket,
    int ncsf_ket,
    int norb,
    int twos_ket_total,
    const double* c_bra,
    int nb,
    const double* c_ket,
    int nk,
    const double* eta_re,
    const double* eta_im,
    const float* sixj_211,
    const float* t_factor,
    int twos_max,
    double* rho_re,
    double* rho_im,
    cudaStream_t stream,
    int threads);

extern "C" void guga_triplet_build_gm_all_m_from_epq_table_launch_stream(
    const int16_t* node_twos,
    const int8_t* steps_table,
    const int32_t* nodes_table,
    int ncsf,
    int norb,
    const int64_t* epq_indptr,
    const int32_t* epq_indices,
    const int32_t* epq_pq,
    const double* c_bra,
    int nb,
    const double* c_ket,
    int nk,
    const double* h_re,
    const double* h_im,
    const float* sixj_211,
    const float* t_factor,
    int twos_max,
    double* gm_re,
    double* gm_im,
    cudaStream_t stream,
    int threads);

extern "C" void guga_triplet_build_gm_all_m_dfs_launch_stream(
    const int32_t* child_bra,
    const int16_t* node_twos_bra,
    const int64_t* child_prefix_bra,
    int root_bra,
    int leaf_bra,
    int ncsf_bra,
    int twos_bra_total,
    const int16_t* node_twos_ket,
    const int8_t* steps_table_ket,
    const int32_t* nodes_table_ket,
    int ncsf_ket,
    int norb,
    int twos_ket_total,
    const double* c_bra,
    int nb,
    const double* c_ket,
    int nk,
    const double* h_re,
    const double* h_im,
    const float* sixj_211,
    const float* t_factor,
    int twos_max,
    double* gm_re,
    double* gm_im,
    cudaStream_t stream,
    int threads);

#endif  // CUGUGA_GPU_GUGA_CUDA_KERNELS_API_H
