#ifndef CUGUGA_GPU_GUGA_CUDA_KERNELS_API_H
#define CUGUGA_GPU_GUGA_CUDA_KERNELS_API_H

#include <cuda_runtime.h>

#include <cstdint>

extern "C" void guga_epq_contribs_one_debug_launch(
    const int32_t* child,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    int norb,
    int csf_idx,
    const int8_t* steps,
    const int32_t* nodes,
    int p,
    int q,
    int max_out,
    int32_t* out_idx,
    double* out_coeff,
    int* out_count,
    int* out_overflow);

extern "C" void guga_epq_apply_g_debug_launch(
    const int32_t* child,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    int norb,
    int csf_idx,
    const int8_t* steps,
    const int32_t* nodes,
    const double* g_flat,
    double thresh_gpq,
    double thresh_contrib,
    int max_out,
    int32_t* out_idx,
    double* out_val,
    int* out_count,
    int* out_overflow,
    int* out_n_pairs);

extern "C" void guga_epq_contribs_many_count_launch(
    const int32_t* child,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    const int8_t* steps_table,
    const int32_t* nodes_table,
    int ncsf,
    int norb,
    const int32_t* task_csf,
    const int32_t* task_p,
    const int32_t* task_q,
    int ntasks,
    int32_t* counts,
    int* overflow_flag,
    int threads);

extern "C" void guga_epq_contribs_many_count_launch_stream(
    const int32_t* child,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    const int8_t* steps_table,
    const int32_t* nodes_table,
    int ncsf,
    int norb,
    const int32_t* task_csf,
    const int32_t* task_p,
    const int32_t* task_q,
    int ntasks,
    int32_t* counts,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" void guga_epq_contribs_many_write_launch(
    const int32_t* child,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    const int8_t* steps_table,
    const int32_t* nodes_table,
    int ncsf,
    int norb,
    const int32_t* task_csf,
    const int32_t* task_p,
    const int32_t* task_q,
    int ntasks,
    const int64_t* offsets,
    int32_t* out_idx,
    double* out_coeff,
    int32_t* out_task_csf,
    int32_t* out_task_pq,
    int* overflow_flag,
    int threads);

extern "C" void guga_epq_contribs_many_write_launch_stream(
    const int32_t* child,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    const int8_t* steps_table,
    const int32_t* nodes_table,
    int ncsf,
    int norb,
    const int32_t* task_csf,
    const int32_t* task_p,
    const int32_t* task_q,
    int ntasks,
    const int64_t* offsets,
    int32_t* out_idx,
    double* out_coeff,
    int32_t* out_task_csf,
    int32_t* out_task_pq,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" void guga_epq_contribs_many_count_allpairs_launch_stream(
    const int32_t* child,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    const int8_t* steps_table,
    const int32_t* nodes_table,
    int ncsf,
    int norb,
    int j_start,
    int j_count,
    int32_t* counts,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" void guga_epq_contribs_many_write_allpairs_launch_stream(
    const int32_t* child,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    const int8_t* steps_table,
    const int32_t* nodes_table,
    int ncsf,
    int norb,
    int j_start,
    int j_count,
    const int64_t* offsets,
    int32_t* out_idx,
    void* out_coeff,
    int out_coeff_type,
    int32_t* out_task_csf,
    void* out_task_pq,
    int out_task_pq_type,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" void guga_epq_contribs_many_fused_allpairs_launch_stream(
    const int32_t* child,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    const int8_t* steps_table,
    const int32_t* nodes_table,
    int ncsf,
    int norb,
    int j_start,
    int j_count,
    int max_out,
    int32_t* out_idx,
    void* out_coeff,
    int out_coeff_type,
    int32_t* out_task_csf,
    void* out_task_pq,
    int out_task_pq_type,
    int* nnz_counter,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" void guga_epq_contribs_many_count_allpairs_recompute_launch_stream(
    const int32_t* child,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    int ncsf,
    int norb,
    int j_start,
    int j_count,
    int32_t* counts,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" void guga_epq_contribs_many_write_allpairs_recompute_launch_stream(
    const int32_t* child,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    int ncsf,
    int norb,
    int j_start,
    int j_count,
    const int64_t* offsets,
    int32_t* out_idx,
    void* out_coeff,
    int out_coeff_type,
    int32_t* out_task_csf,
    void* out_task_pq,
    int out_task_pq_type,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" void guga_epq_contribs_many_count_allpairs_recompute_warp_launch_stream(
    const int32_t* child,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    int ncsf,
    int norb,
    int j_start,
    int j_count,
    int32_t* counts,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" void guga_epq_contribs_many_write_allpairs_recompute_warp_launch_stream(
    const int32_t* child,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    int ncsf,
    int norb,
    int j_start,
    int j_count,
    const int64_t* offsets,
    int32_t* out_idx,
    void* out_coeff,
    int out_coeff_type,
    int32_t* out_task_csf,
    void* out_task_pq,
    int out_task_pq_type,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t guga_qmc_pack_scaled_identity_i32_f64_launch_stream(
    const int32_t* x_idx,
    const double* x_val,
    int n,
    double scale,
    int32_t* idx_out,
    double* val_out,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t guga_qmc_pack_scaled_identity_u64_f64_launch_stream(
    const uint64_t* x_key,
    const double* x_val,
    int n,
    double scale,
    uint64_t* key_out,
    double* val_out,
    cudaStream_t stream,
    int threads);

// Batched dot products for many pairs of sorted sparse vectors.
//
// Inputs are packed row-major matrices. For A (nA, stride_a):
//   - vector i uses a_idx[i, :a_nnz[i]] and a_val[i, :a_nnz[i]] (sorted by idx).
// Similarly for B (nB, stride_b).
//
// Output is dense row-major out (nA, nB): out[i, j] = dot(A_i, B_j).
extern "C" cudaError_t guga_qmc_sparse_dot_many_sorted_i32_f64_launch_stream(
    const int32_t* a_idx,
    const double* a_val,
    const int32_t* a_nnz,
    int nA,
    int stride_a,
    const int32_t* b_idx,
    const double* b_val,
    const int32_t* b_nnz,
    int nB,
    int stride_b,
    double* out,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t guga_qmc_spawn_one_body_launch_stream(
    const int32_t* child,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    const int8_t* steps_table,
    const int32_t* nodes_table,
    int ncsf,
    int norb,
    const int32_t* x_idx,
    const double* x_val,
    int m,
    const double* h_eff_flat,
    double eps,
    int nspawn,
    uint64_t seed,
    double initiator_t,
    int32_t* out_idx,
    double* out_val,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t guga_qmc_spawn_hamiltonian_launch_stream(
    const int32_t* child,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    const int8_t* steps_table,
    const int32_t* nodes_table,
    int ncsf,
    int norb,
    const int32_t* x_idx,
    const double* x_val,
    int m,
    const double* h_base_flat,
    const double* eri_mat,
    double eps,
    int nspawn_one,
    int nspawn_two,
    uint64_t seed,
    double initiator_t,
    int32_t* out_idx,
    double* out_val,
    cudaStream_t stream,
    int threads);

// Variant that reads initiator threshold from device memory (scalar double on device).
// This allows callers to compute initiator_t on the GPU without a host sync.
extern "C" cudaError_t guga_qmc_spawn_hamiltonian_initiator_dev_launch_stream(
    const int32_t* child,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    const int8_t* steps_table,
    const int32_t* nodes_table,
    int ncsf,
    int norb,
    const int32_t* x_idx,
    const double* x_val,
    int m,
    const double* h_base_flat,
    const double* eri_mat,
    double eps,
    int nspawn_one,
    int nspawn_two,
    uint64_t seed,
    const double* initiator_t_dev,
    int32_t* out_idx,
    double* out_val,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t guga_qmc_spawn_hamiltonian_u64_f64_launch_stream(
    const int32_t* child,
    const int16_t* node_twos,
    int norb,
    const uint64_t* x_key,
    const double* x_val,
    int m,
    const double* h_base_flat,
    const double* eri_mat,
    const float* pair_alias_prob,
    const int32_t* pair_alias_idx,
    const double* pair_norm,
    double pair_norm_sum,
    int pair_sampling_mode,
    double eps,
    int nspawn_one,
    int nspawn_two,
    uint64_t seed,
    double initiator_t,
    uint64_t* out_key,
    double* out_val,
    cudaStream_t stream,
    int threads);

// Variant that reads initiator threshold from device memory (scalar double on device).
// This allows callers to compute initiator_t on the GPU without a host sync.
extern "C" cudaError_t guga_qmc_spawn_hamiltonian_u64_f64_initiator_dev_launch_stream(
    const int32_t* child,
    const int16_t* node_twos,
    int norb,
    const uint64_t* x_key,
    const double* x_val,
    int m,
    const double* h_base_flat,
    const double* eri_mat,
    const float* pair_alias_prob,
    const int32_t* pair_alias_idx,
    const double* pair_norm,
    double pair_norm_sum,
    int pair_sampling_mode,
    double eps,
    int nspawn_one,
    int nspawn_two,
    uint64_t seed,
    const double* initiator_t_dev,
    uint64_t* out_key,
    double* out_val,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t guga_qmc_spawn_hamiltonian_idx64_u64_f64_launch_stream(
    const int32_t* child,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    uint64_t ncsf,
    int norb,
    const uint64_t* x_idx_u64,
    const double* x_val,
    int m,
    const double* h_base_flat,
    const double* eri_mat,
    const float* pair_alias_prob,
    const int32_t* pair_alias_idx,
    const double* pair_norm,
    double pair_norm_sum,
    int pair_sampling_mode,
    double eps,
    int nspawn_one,
    int nspawn_two,
    uint64_t seed,
    double initiator_t,
    uint64_t* out_idx_u64,
    double* out_val,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t guga_qmc_spawn_hamiltonian_idx64_u64_f64_initiator_dev_launch_stream(
    const int32_t* child,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    uint64_t ncsf,
    int norb,
    const uint64_t* x_idx_u64,
    const double* x_val,
    int m,
    const double* h_base_flat,
    const double* eri_mat,
    const float* pair_alias_prob,
    const int32_t* pair_alias_idx,
    const double* pair_norm,
    double pair_norm_sum,
    int pair_sampling_mode,
    double eps,
    int nspawn_one,
    int nspawn_two,
    uint64_t seed,
    const double* initiator_t_dev,
    uint64_t* out_idx_u64,
    double* out_val,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t guga_qmc_coalesce_coo_i32_f64_launch_stream(
    const int32_t* idx_in,
    const double* val_in,
    int n,
    int32_t* idx_out,
    double* val_out,
    int* out_nnz,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t guga_qmc_coalesce_coo_u64_f64_launch_stream(
    const uint64_t* key_in,
    const double* val_in,
    int n,
    uint64_t* key_out,
    double* val_out,
    int* out_nnz,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t guga_qmc_phi_pivot_resample_i32_f64_launch_stream(
    const int32_t* idx_in,
    const double* val_in,
    int n_in,
    int32_t* idx_out,
    double* val_out,
    int* out_nnz,
    int m,
    int pivot,
    uint64_t seed,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t guga_qmc_phi_pivot_resample_u64_f64_launch_stream(
    const uint64_t* key_in,
    const double* val_in,
    int n_in,
    uint64_t* key_out,
    double* val_out,
    int* out_nnz,
    int m,
    int pivot,
    uint64_t seed,
    cudaStream_t stream,
    int threads);

extern "C" void* guga_qmc_workspace_create(int max_n, int max_m);

extern "C" void guga_qmc_workspace_destroy(void* ws_handle);

extern "C" void* guga_qmc_workspace_u64_create(int max_n, int max_m);

extern "C" void guga_qmc_workspace_u64_destroy(void* ws_handle);

extern "C" cudaError_t guga_qmc_coalesce_coo_i32_f64_ws_launch_stream(
    void* ws_handle,
    const int32_t* idx_in,
    const double* val_in,
    int n,
    int32_t* idx_out,
    double* val_out,
    int* out_nnz,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t guga_qmc_coalesce_coo_u64_f64_ws_launch_stream(
    void* ws_handle,
    const uint64_t* key_in,
    const double* val_in,
    int n,
    uint64_t* key_out,
    double* val_out,
    int* out_nnz,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t guga_qmc_phi_pivot_resample_i32_f64_ws_launch_stream(
    void* ws_handle,
    const int32_t* idx_in,
    const double* val_in,
    int n_in,
    int32_t* idx_out,
    double* val_out,
    int* out_nnz,
    int m,
    int pivot,
    uint64_t seed,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t guga_qmc_phi_pivot_resample_u64_f64_ws_launch_stream(
    void* ws_handle,
    const uint64_t* key_in,
    const double* val_in,
    int n_in,
    uint64_t* key_out,
    double* val_out,
    int* out_nnz,
    int m,
    int pivot,
    uint64_t seed,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t guga_counts_to_offsets_exclusive_scan_launch(
    const int32_t* counts,
    int ntasks,
    int64_t* offsets,
    int64_t* total_host);

extern "C" cudaError_t guga_counts_to_offsets_exclusive_scan_launch_stream(
    const int32_t* counts,
    int ntasks,
    int64_t* offsets,
    int64_t* total_host,
    cudaStream_t stream);

extern "C" cudaError_t guga_ell_spmv_f64_launch_stream(
    const int32_t* col_idx,
    const double* val,
    int nrows,
    int width,
    const double* x,
    double* y,
    int add,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t guga_ell_spmm_f64_launch_stream(
    const int32_t* col_idx,
    const double* val,
    int nrows,
    int width,
    const double* x,
    int ldx,
    double* y,
    int ldy,
    int nvec,
    int add,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t guga_sell_spmv_f64_launch_stream(
    const int64_t* slice_ptr,
    const int32_t* slice_width,
    const int32_t* col_idx,
    const double* val,
    int nrows,
    int slice_height,
    const double* x,
    double* y,
    int add,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t guga_sell_spmm_f64_launch_stream(
    const int64_t* slice_ptr,
    const int32_t* slice_width,
    const int32_t* col_idx,
    const double* val,
    int nrows,
    int slice_height,
    const double* x,
    int ldx,
    double* y,
    int ldy,
    int nvec,
    int add,
    cudaStream_t stream,
    int threads);

extern "C" void guga_epq_apply_gather_inplace_launch_stream(
    const int32_t* child,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    const int8_t* steps_table,
    const int32_t* nodes_table,
    int ncsf,
    int norb,
    int p,
    int q,
    const double* x,
    int ldx,
    int nvec,
    double alpha,
    double* y,
    int ldy,
    int add,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" void launch_scatter_embed(
    const double* x_sub,
    const int64_t* sub_to_full,
    double* x_full,
    int nsub,
    int threads,
    cudaStream_t stream);

extern "C" void launch_gather_project(
    const double* y_full,
    const int64_t* sub_to_full,
    double* y_sub,
    int nsub,
    int threads,
    cudaStream_t stream);

extern "C" void guga_epq_apply_weighted_many_atomic_launch(
    const int32_t* child,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    const int8_t* steps_table,
    const int32_t* nodes_table,
    int ncsf,
    int norb,
    const int32_t* task_csf,
    const int32_t* task_p,
    const int32_t* task_q,
    const double* task_wgt,
    const double* task_scale,
    int ntasks,
    double* y,
    int* overflow_flag,
    int threads);

extern "C" void guga_apply_g_flat_scatter_atomic_launch(
    const int32_t* child,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    const int8_t* steps_table,
    const int32_t* nodes_table,
    int ncsf,
    int norb,
    const int32_t* task_csf,
    const double* task_scale,
    const double* task_g,
    int64_t g_stride,
    int ntasks,
    double* y,
    int* overflow_flag,
    int threads);

extern "C" void guga_apply_g_flat_task_sums_launch(
    const int32_t* child,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    const int8_t* steps_table,
    const int32_t* nodes_table,
    int ncsf,
    int norb,
    const int32_t* task_csf,
    const double* task_scale,
    const double* task_g,
    int64_t g_stride,
    int ntasks,
    double* out_sum,
    int* overflow_flag,
    int threads);

extern "C" void guga_apply_g_flat_scatter_atomic_launch_stream(
    const int32_t* child,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    const int8_t* steps_table,
    const int32_t* nodes_table,
    int ncsf,
    int norb,
    const int32_t* task_csf,
    const double* task_scale,
    const double* task_g,
    int64_t g_stride,
    int ntasks,
    double* y,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" void guga_apply_g_flat_scatter_atomic_f32_launch(
    const int32_t* child,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    const int8_t* steps_table,
    const int32_t* nodes_table,
    int ncsf,
    int norb,
    const int32_t* task_csf,
    const float* task_scale,
    const float* task_g,
    int64_t g_stride,
    int ntasks,
    float* y,
    int* overflow_flag,
    int threads);

extern "C" void guga_apply_g_flat_scatter_atomic_f32_launch_stream(
    const int32_t* child,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    const int8_t* steps_table,
    const int32_t* nodes_table,
    int ncsf,
    int norb,
    const int32_t* task_csf,
    const float* task_scale,
    const float* task_g,
    int64_t g_stride,
    int ntasks,
    float* y,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" void guga_apply_g_flat_scatter_atomic_epq_table_launch_stream(
    const int8_t* steps_table,
    int ncsf,
    int norb,
    const void* epq_indptr,
    int epq_indptr_type,
    const int32_t* epq_indices,
    const void* epq_pq,
    int epq_pq_type,
    const double* epq_data,
    const int32_t* task_csf,
    const double* task_scale,
    const double* task_g,
    int64_t g_stride,
    int ntasks,
    double* y,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" void guga_apply_g_flat_gather_epq_table_launch_stream(
    const int8_t* steps_table,
    int ncsf,
    int norb,
    const void* epq_t_indptr,
    int epq_t_indptr_type,
    const int32_t* epq_t_source,
    const void* epq_t_pq,
    int epq_t_pq_type,
    const double* epq_t_data,
    const int32_t* task_row_by_csf,
    const double* task_scale_by_csf,
    const double* task_g,
    int64_t g_stride,
    double* y,
    int* overflow_flag,
    cudaStream_t stream,
    int threads,
    int add);

extern "C" void guga_apply_g_flat_gather_epq_table_mixed_launch_stream(
    const int8_t* steps_table,
    int ncsf,
    int norb,
    const void* epq_t_indptr,
    int epq_t_indptr_type,
    const int32_t* epq_t_source,
    const void* epq_t_pq,
    int epq_t_pq_type,
    const float* epq_t_data,
    const int32_t* task_row_by_csf,
    const double* task_scale_by_csf,
    const double* task_g,
    int64_t g_stride,
    double* y,
    int* overflow_flag,
    cudaStream_t stream,
    int threads,
    int add);

extern "C" void guga_apply_g_flat_scatter_atomic_epq_table_f32_launch_stream(
    const int8_t* steps_table,
    int ncsf,
    int norb,
    const void* epq_indptr,
    int epq_indptr_type,
    const int32_t* epq_indices,
    const void* epq_pq,
    int epq_pq_type,
    const float* epq_data,
    const int32_t* task_csf,
    const float* task_scale,
    const float* task_g,
    int64_t g_stride,
    int ntasks,
    float* y,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" void guga_apply_g_flat_scatter_atomic_epq_table_mixed_launch_stream(
    const int8_t* steps_table,
    int ncsf,
    int norb,
    const void* epq_indptr,
    int epq_indptr_type,
    const int32_t* epq_indices,
    const void* epq_pq,
    int epq_pq_type,
    const float* epq_data,
    const int32_t* task_csf,
    const double* task_scale,
    const double* task_g,
    int64_t g_stride,
    int ntasks,
    double* y,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" void guga_apply_g_flat_scatter_atomic_epq_table_tile_launch_stream(
    const int8_t* steps_table,
    int ncsf,
    int norb,
    const int64_t* local_indptr,
    const int32_t* epq_indices,
    const void* epq_pq,
    int epq_pq_type,
    const double* epq_data,
    const double* task_g,
    int64_t g_stride,
    const double* task_scale,
    int j_start,
    int j_count,
    double* y,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" void guga_apply_g_flat_scatter_atomic_epq_table_tile_f32_launch_stream(
    const int8_t* steps_table,
    int ncsf,
    int norb,
    const int64_t* local_indptr,
    const int32_t* epq_indices,
    const void* epq_pq,
    int epq_pq_type,
    const float* epq_data,
    const float* task_g,
    int64_t g_stride,
    const float* task_scale,
    int j_start,
    int j_count,
    float* y,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" void guga_apply_g_flat_scatter_atomic_epq_table_tile_f32_kahan_launch_stream(
    const int8_t* steps_table,
    int ncsf,
    int norb,
    const int64_t* local_indptr,
    const int32_t* epq_indices,
    const void* epq_pq,
    int epq_pq_type,
    const float* epq_data,
    const float* task_g,
    int64_t g_stride,
    const float* task_scale,
    int j_start,
    int j_count,
    float* y,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" void guga_apply_g_flat_scatter_atomic_epq_table_tile_mixed_launch_stream(
    const int8_t* steps_table,
    int ncsf,
    int norb,
    const int64_t* local_indptr,
    const int32_t* epq_indices,
    const void* epq_pq,
    int epq_pq_type,
    const float* epq_data,
    const double* task_g,
    int64_t g_stride,
    const double* task_scale,
    int j_start,
    int j_count,
    double* y,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" void guga_apply_g_flat_gather_epq_table_f32_launch_stream(
    const int8_t* steps_table,
    int ncsf,
    int norb,
    const void* epq_t_indptr,
    int epq_t_indptr_type,
    const int32_t* epq_t_source,
    const void* epq_t_pq,
    int epq_t_pq_type,
    const float* epq_t_data,
    const int32_t* task_row_by_csf,
    const float* task_scale_by_csf,
    const float* task_g,
    int64_t g_stride,
    float* y,
    int* overflow_flag,
    cudaStream_t stream,
    int threads,
    int add);

extern "C" void guga_apply_csr_eri_mat_fused_epq_table_range_launch_stream(
    const int8_t* steps_table,
    int ncsf,
    int norb,
    const int64_t* epq_indptr,
    const int32_t* epq_indices,
    const void* epq_pq,
    int epq_pq_type,
    const double* epq_data,
    const int32_t* row_j,
    const int32_t* row_k,
    const int64_t* csr_indptr,
    const int32_t* csr_indices,
    const double* csr_data,
    int row_start,
    int nrows,
    const double* eri_mat_t,
    int nops,
    double half,
    const double* x,
    double* y,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" void guga_apply_csr_eri_mat_fused_epq_table_range_f64_out_f32_coeff_launch_stream(
    const int8_t* steps_table,
    int ncsf,
    int norb,
    const int64_t* epq_indptr,
    const int32_t* epq_indices,
    const void* epq_pq,
    int epq_pq_type,
    const float* epq_data,
    const int32_t* row_j,
    const int32_t* row_k,
    const int64_t* csr_indptr,
    const int32_t* csr_indices,
    const double* csr_data,
    int row_start,
    int nrows,
    const double* eri_mat_t,
    int nops,
    double half,
    const double* x,
    double* y,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" void guga_apply_csr_eri_mat_fused_epq_table_range_f32_launch_stream(
    const int8_t* steps_table,
    int ncsf,
    int norb,
    const int64_t* epq_indptr,
    const int32_t* epq_indices,
    const void* epq_pq,
    int epq_pq_type,
    const float* epq_data,
    const int32_t* row_j,
    const int32_t* row_k,
    const int64_t* csr_indptr,
    const int32_t* csr_indices,
    const float* csr_data,
    int row_start,
    int nrows,
    const float* eri_mat_t,
    int nops,
    float half,
    const float* x,
    float* y,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

// Kahan-compensated FP32 gather kernel (Neumaier compensated summation).
extern "C" void guga_apply_g_flat_gather_epq_table_f32_kahan_launch_stream(
    const int8_t* steps_table,
    int ncsf,
    int norb,
    const void* epq_t_indptr,
    int epq_t_indptr_type,
    const int32_t* epq_t_source,
    const void* epq_t_pq,
    int epq_t_pq_type,
    const float* epq_t_data,
    const int32_t* task_row_by_csf,
    const float* task_scale_by_csf,
    const float* task_g,
    int64_t g_stride,
    float* y,
    int* overflow_flag,
    cudaStream_t stream,
    int threads,
    int add);

extern "C" void guga_apply_g_flat_gather_epq_transpose_range_launch_stream(
    const int8_t* steps_table,
    int ncsf,
    int norb,
    const void* epq_t_indptr,
    int epq_t_indptr_type,
    const int32_t* epq_t_source,
    const void* epq_t_pq,
    int epq_t_pq_type,
    const double* epq_t_data,
    const double* g_block,
    int64_t g_stride,
    int k_start,
    int k_count,
    double* y,
    int* overflow_flag,
    cudaStream_t stream,
    int threads,
    int add);

// Pair-indexed Apply: reads g_block via full_to_pair index mapping.
extern "C" void guga_apply_g_pair_gather_epq_transpose_range_launch_stream(
    const int8_t* steps_table,
    int ncsf,
    int norb,
    const void* epq_t_indptr,
    int epq_t_indptr_type,
    const int32_t* epq_t_source,
    const void* epq_t_pq,
    int epq_t_pq_type,
    const double* epq_t_data,
    const double* g_block,
    int64_t g_stride,
    int k_start,
    int k_count,
    const int32_t* full_to_pair,
    double* y,
    int* overflow_flag,
    cudaStream_t stream,
    int threads,
    int add);

extern "C" void guga_apply_g_flat_gather_epq_transpose_range_mixed_launch_stream(
    const int8_t* steps_table,
    int ncsf,
    int norb,
    const void* epq_t_indptr,
    int epq_t_indptr_type,
    const int32_t* epq_t_source,
    const void* epq_t_pq,
    int epq_t_pq_type,
    const float* epq_t_data,
    const double* g_block,
    int64_t g_stride,
    int k_start,
    int k_count,
    double* y,
    int* overflow_flag,
    cudaStream_t stream,
    int threads,
    int add);

extern "C" void guga_apply_g_flat_gather_epq_transpose_range_f32_launch_stream(
    const int8_t* steps_table,
    int ncsf,
    int norb,
    const void* epq_t_indptr,
    int epq_t_indptr_type,
    const int32_t* epq_t_source,
    const void* epq_t_pq,
    int epq_t_pq_type,
    const float* epq_t_data,
    const float* g_block,
    int64_t g_stride,
    int k_start,
    int k_count,
    float* y,
    int* overflow_flag,
    cudaStream_t stream,
    int threads,
    int add);

extern "C" void guga_apply_g_flat_gather_epq_transpose_range_f32_kahan_launch_stream(
    const int8_t* steps_table,
    int ncsf,
    int norb,
    const void* epq_t_indptr,
    int epq_t_indptr_type,
    const int32_t* epq_t_source,
    const void* epq_t_pq,
    int epq_t_pq_type,
    const float* epq_t_data,
    const float* g_block,
    int64_t g_stride,
    int k_start,
    int k_count,
    float* y,
    int* overflow_flag,
    cudaStream_t stream,
    int threads,
    int add);

// Kahan-compensated FP32 fused CSR+EPQ kernel.
extern "C" void guga_apply_csr_eri_mat_fused_epq_table_range_f32_kahan_launch_stream(
    const int8_t* steps_table,
    int ncsf,
    int norb,
    const int64_t* epq_indptr,
    const int32_t* epq_indices,
    const void* epq_pq,
    int epq_pq_type,
    const float* epq_data,
    const int32_t* row_j,
    const int32_t* row_k,
    const int64_t* csr_indptr,
    const int32_t* csr_indices,
    const float* csr_data,
    int row_start,
    int nrows,
    const float* eri_mat_t,
    int nops,
    float half,
    const float* x,
    float* y,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" void guga_build_w_from_csr_unitnnz_launch_stream(
    const int32_t* row_j,
    const int32_t* row_k,
    const int32_t* csr_rs,
    const double* csr_c,
    int nrows,
    const double* x,
    int ncsf,
    int nops,
    double* w_out,
    int64_t w_stride,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" void guga_build_w_from_csr_bucket0_launch_stream(
    const int32_t* row_perm,
    const int32_t* row_j,
    const int32_t* row_k,
    const int64_t* csr_indptr,
    const int32_t* csr_indices,
    const double* csr_data,
    int n_bucket0,
    const double* x,
    int ncsf,
    int nops,
    double* w_out,
    int64_t w_stride,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" void guga_apply_csr_narrow_fused_epq_perm_launch_stream(
    const int8_t* steps_table,
    int ncsf,
    int norb,
    const int64_t* epq_indptr,
    const int32_t* epq_indices,
    const void* epq_pq,
    int epq_pq_type,
    const double* epq_data,
    const int32_t* row_j,
    const int32_t* row_k,
    const int64_t* csr_indptr,
    const int32_t* csr_indices,
    const double* csr_data,
    const int32_t* row_perm,
    int nrows,
    const double* eri_mat_t,
    int nops,
    double half,
    const double* x,
    double* y,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" void guga_apply_csr_eri_mat_fused_epq_table_range_perm_launch_stream(
    const int8_t* steps_table,
    int ncsf,
    int norb,
    const int64_t* epq_indptr,
    const int32_t* epq_indices,
    const void* epq_pq,
    int epq_pq_type,
    const double* epq_data,
    const int32_t* row_j,
    const int32_t* row_k,
    const int64_t* csr_indptr,
    const int32_t* csr_indices,
    const double* csr_data,
    const int32_t* row_perm,
    int nrows,
    const double* eri_mat_t,
    int nops,
    double half,
    const double* x,
    double* y,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" void guga_build_w_from_epq_table_launch_stream(
    const void* epq_indptr,
    int epq_indptr_type,
    const int32_t* epq_indices,
    const void* epq_pq,
    int epq_pq_type,
    const double* epq_data,
    const double* x,
    int ncsf,
    int nops,
    double* w_out,
    int64_t w_stride,
    int* overflow_flag,
    cudaStream_t stream,
    int threads,
    int k_start,
    int k_count);

extern "C" void guga_build_w_from_epq_transpose_range_launch_stream(
    const void* epq_t_indptr,
    int epq_t_indptr_type,
    const int32_t* epq_t_source,
    const void* epq_t_pq,
    int epq_t_pq_type,
    const double* epq_t_data,
    const double* x,
    int ncsf,
    int nops,
    double* w_out,
    int64_t w_stride,
    int* overflow_flag,
    cudaStream_t stream,
    int threads,
    int k_start,
    int k_count);

// Pair-indexed W-build: writes to pair-indexed output via full_to_pair.
extern "C" void guga_build_w_pair_from_epq_transpose_range_launch_stream(
    const void* epq_t_indptr,
    int epq_t_indptr_type,
    const int32_t* epq_t_source,
    const void* epq_t_pq,
    int epq_t_pq_type,
    const double* epq_t_data,
    const double* x,
    int ncsf,
    int nops,
    int ncol,
    const int32_t* full_to_pair,
    double* w_out,
    int64_t w_stride,
    int* overflow_flag,
    cudaStream_t stream,
    int threads,
    int k_start,
    int k_count);

// Build W from an EPQ transpose table for multiple vectors, and apply a fused
// per-row-per-p scaling:
//   W_scaled[k_local, (pq*nvec + v)] = (E_pq |x[:,v]>)[k] * (hdiag[k] - epsa[p])
// Includes diagonal E_pp contributions from steps_table.
extern "C" void guga_build_w_from_epq_transpose_range_mm_scaled_launch_stream(
    const int8_t* steps_table,
    int ncsf,
    int norb,
    const void* epq_t_indptr,
    int epq_t_indptr_type,
    const int32_t* epq_t_source,
    const void* epq_t_pq,
    int epq_t_pq_type,
    const double* epq_t_data,
    const double* x,
    int64_t x_stride,
    int nvec,
    const double* hdiag,
    const double* epsa,
    double* w_out,
    int64_t w_stride,
    int* overflow_flag,
    cudaStream_t stream,
    int threads,
    int k_start,
    int k_count);

// Build W from an EPQ transpose table for multiple vectors:
//   W[k_local, (pq*nvec + v)] = (E_pq |x[:,v]>)[k]
// Includes diagonal E_pp contributions from steps_table.
extern "C" void guga_build_w_from_epq_transpose_range_mm_launch_stream(
    const int8_t* steps_table,
    int ncsf,
    int norb,
    const void* epq_t_indptr,
    int epq_t_indptr_type,
    const int32_t* epq_t_source,
    const void* epq_t_pq,
    int epq_t_pq_type,
    const double* epq_t_data,
    const double* x,
    int64_t x_stride,
    int nvec,
    double* w_out,
    int64_t w_stride,
    int* overflow_flag,
    cudaStream_t stream,
    int threads,
    int k_start,
    int k_count);

extern "C" void guga_build_w_from_epq_transpose_range_mm_scaled_f64_out_f32_coeff_launch_stream(
    const int8_t* steps_table,
    int ncsf,
    int norb,
    const void* epq_t_indptr,
    int epq_t_indptr_type,
    const int32_t* epq_t_source,
    const void* epq_t_pq,
    int epq_t_pq_type,
    const float* epq_t_data,
    const double* x,
    int64_t x_stride,
    int nvec,
    const double* hdiag,
    const double* epsa,
    double* w_out,
    int64_t w_stride,
    int* overflow_flag,
    cudaStream_t stream,
    int threads,
    int k_start,
    int k_count);

extern "C" void guga_build_w_from_epq_transpose_range_mm_f64_out_f32_coeff_launch_stream(
    const int8_t* steps_table,
    int ncsf,
    int norb,
    const void* epq_t_indptr,
    int epq_t_indptr_type,
    const int32_t* epq_t_source,
    const void* epq_t_pq,
    int epq_t_pq_type,
    const float* epq_t_data,
    const double* x,
    int64_t x_stride,
    int nvec,
    double* w_out,
    int64_t w_stride,
    int* overflow_flag,
    cudaStream_t stream,
    int threads,
    int k_start,
    int k_count);

extern "C" void guga_build_w_from_epq_transpose_range_f64_out_f32_coeff_launch_stream(
    const void* epq_t_indptr,
    int epq_t_indptr_type,
    const int32_t* epq_t_source,
    const void* epq_t_pq,
    int epq_t_pq_type,
    const float* epq_t_data,
    const double* x,
    int ncsf,
    int nops,
    double* w_out,
    int64_t w_stride,
    int* overflow_flag,
    cudaStream_t stream,
    int threads,
    int k_start,
    int k_count);

extern "C" void guga_build_w_from_epq_table_f32_launch_stream(
    const void* epq_indptr,
    int epq_indptr_type,
    const int32_t* epq_indices,
    const void* epq_pq,
    int epq_pq_type,
    const float* epq_data,
    const float* x,
    int ncsf,
    int nops,
    float* w_out,
    int64_t w_stride,
    int* overflow_flag,
    cudaStream_t stream,
    int threads,
    int k_start,
    int k_count);

extern "C" void guga_build_w_from_epq_table_f64_out_f32_coeff_launch_stream(
    const void* epq_indptr,
    int epq_indptr_type,
    const int32_t* epq_indices,
    const void* epq_pq,
    int epq_pq_type,
    const float* epq_data,
    const double* x,
    int ncsf,
    int nops,
    double* w_out,
    int64_t w_stride,
    int* overflow_flag,
    cudaStream_t stream,
    int threads,
    int k_start,
    int k_count);

extern "C" void guga_build_w_from_epq_transpose_range_f32_launch_stream(
    const void* epq_t_indptr,
    int epq_t_indptr_type,
    const int32_t* epq_t_source,
    const void* epq_t_pq,
    int epq_t_pq_type,
    const float* epq_t_data,
    const float* x,
    int ncsf,
    int nops,
    float* w_out,
    int64_t w_stride,
    int* overflow_flag,
    cudaStream_t stream,
    int threads,
    int k_start,
    int k_count);

extern "C" void guga_build_t_from_epq_table_launch_stream(
    const int8_t* steps_table,
    const int64_t* epq_indptr,
    const int32_t* epq_indices,
    const void* epq_pq,
    int epq_pq_type,
    const double* epq_data,
    const double* c_vec,
    int ncsf,
    int norb,
    int nops,
    double* t_out,
    int64_t t_stride,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" void guga_build_t_from_epq_table_f32_launch_stream(
    const int8_t* steps_table,
    const int64_t* epq_indptr,
    const int32_t* epq_indices,
    const void* epq_pq,
    int epq_pq_type,
    const float* epq_data,
    const float* c_vec,
    int ncsf,
    int norb,
    int nops,
    float* t_out,
    int64_t t_stride,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" void guga_apply_g_flat_task_sums_launch_stream(
    const int32_t* child,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    const int8_t* steps_table,
    const int32_t* nodes_table,
    int ncsf,
    int norb,
    const int32_t* task_csf,
    const double* task_scale,
    const double* task_g,
    int64_t g_stride,
    int ntasks,
    double* out_sum,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t guga_build_w_diag_from_steps_launch_stream(
    const int8_t* steps_table,
    int ncsf,
    int norb,
    int j_start,
    int j_count,
    const double* x,
    int nops,
    double* w_out,
    int64_t w_stride,
    cudaStream_t stream,
    int threads,
    int relative_w);

// Pair-indexed W-diag: writes diagonal via full_to_pair.
extern "C" cudaError_t guga_build_w_diag_pair_from_steps_launch_stream(
    const int8_t* steps_table,
    int ncsf,
    int norb,
    int j_start,
    int j_count,
    const double* x,
    int nops,
    const int32_t* full_to_pair,
    double* w_out,
    int64_t w_stride,
    cudaStream_t stream,
    int threads,
    int relative_w);

extern "C" cudaError_t guga_build_w_diag_from_steps_f32_launch_stream(
    const int8_t* steps_table,
    int ncsf,
    int norb,
    int j_start,
    int j_count,
    const float* x,
    int nops,
    float* w_out,
    int64_t w_stride,
    cudaStream_t stream,
    int threads,
    int relative_w);

extern "C" cudaError_t guga_build_occ_block_from_steps_launch_stream(
    const int8_t* steps_table,
    int ncsf,
    int norb,
    int j_start,
    int j_count,
    double* occ_out,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t guga_build_hdiag_det_guess_from_steps_launch_stream(
    const int8_t* steps_table,
    int ncsf,
    int norb,
    int neleca_det,
    const double* h1e_diag,
    const double* eri_ppqq,
    const double* eri_pqqp,
    double* hdiag_out,
    cudaStream_t stream,
    int threads);

extern "C" void guga_build_t_block_epq_atomic_launch(
    const int32_t* child,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    const int8_t* steps_table,
    const int32_t* nodes_table,
    int ncsf,
    int norb,
    const double* c,
    const int32_t* p_list,
    const int32_t* q_list,
    int nops_block,
    double* out,
    int64_t out_stride,
    int* overflow_flag,
    int threads);

extern "C" void guga_build_t_block_epq_atomic_launch_stream(
    const int32_t* child,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    const int8_t* steps_table,
    const int32_t* nodes_table,
    int ncsf,
    int norb,
    const double* c,
    const int32_t* p_list,
    const int32_t* q_list,
    int nops_block,
    double* out,
    int64_t out_stride,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t guga_kernel25_build_csr_launch(
    const int32_t* j,
    const int32_t* k,
    const int32_t* rs,
    const double* c,
    int nnz_in,
    int coalesce,
    uint64_t* out_row_jk,
    int64_t* out_indptr,
    int32_t* out_indices,
    double* out_data,
    int* out_nrows,
    int* out_nnz);

extern "C" cudaError_t guga_kernel25_build_csr_launch_stream(
    const int32_t* j,
    const int32_t* k,
    const int32_t* rs,
    const double* c,
    int nnz_in,
    int coalesce,
    uint64_t* out_row_jk,
    int64_t* out_indptr,
    int32_t* out_indices,
    double* out_data,
    int* out_nrows,
    int* out_nnz,
    cudaStream_t stream);

extern "C" cudaError_t guga_init_segment_lut();

extern "C" cudaError_t guga_build_g_from_csr_eri_mat_launch(
    const int64_t* indptr,
    const int32_t* indices,
    const double* data,
    int nrows,
    const double* eri_mat,
    int nops,
    double half,
    double* g_out,
    int threads);

extern "C" cudaError_t guga_build_g_from_csr_eri_mat_launch_stream(
    const int64_t* indptr,
    const int32_t* indices,
    const double* data,
    int nrows,
    const double* eri_mat,
    int nops,
    double half,
    double* g_out,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t guga_build_g_from_csr_eri_mat_f64_launch_stream(
    const int64_t* indptr,
    const int32_t* indices,
    const double* data,
    int nrows,
    const double* eri_mat,
    int nops,
    double half,
    double* g_out,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t guga_build_g_from_csr_eri_mat_f32_launch_stream(
    const int64_t* indptr,
    const int32_t* indices,
    const float* data,
    int nrows,
    const float* eri_mat,
    int nops,
    float half,
    float* g_out,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t guga_build_g_from_csr_eri_mat_range_launch_stream(
    const int64_t* indptr,
    const int32_t* indices,
    const double* data,
    int row_start,
    int nrows,
    const double* eri_mat,
    int nops,
    double half,
    double* g_out,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t guga_build_g_from_csr_eri_mat_range_f64_launch_stream(
    const int64_t* indptr,
    const int32_t* indices,
    const double* data,
    int row_start,
    int nrows,
    const double* eri_mat,
    int nops,
    double half,
    double* g_out,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t guga_build_g_from_csr_eri_mat_range_f32_launch_stream(
    const int64_t* indptr,
    const int32_t* indices,
    const float* data,
    int row_start,
    int nrows,
    const float* eri_mat,
    int nops,
    float half,
    float* g_out,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t guga_csr_to_dense_f64_launch_stream(
    const int64_t* indptr,
    const int32_t* indices,
    const double* data,
    int nrows,
    int ncols,
    double* out_dense,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t guga_csr_to_dense_f64_range_launch_stream(
    const int64_t* indptr,
    const int32_t* indices,
    const double* data,
    int row_start,
    int nrows,
    int ncols,
    double* out_dense,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t guga_csr_to_dense_f32_launch_stream(
    const int64_t* indptr,
    const int32_t* indices,
    const float* data,
    int nrows,
    int ncols,
    float* out_dense,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t guga_csr_to_dense_f32_range_launch_stream(
    const int64_t* indptr,
    const int32_t* indices,
    const float* data,
    int row_start,
    int nrows,
    int ncols,
    float* out_dense,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t guga_csr_l_full_to_wt_f64_range_launch_stream(
    const int64_t* indptr,
    const int32_t* indices,
    const double* data,
    int row_start,
    int nrows,
    const double* l_full,
    int naux,
    double* wt_out,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t guga_csr_l_full_to_wt_f32_range_launch_stream(
    const int64_t* indptr,
    const int32_t* indices,
    const float* data,
    int row_start,
    int nrows,
    const float* l_full,
    int naux,
    float* wt_out,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t guga_csr_l_full_to_wt_f32_from_f64_range_launch_stream(
    const int64_t* indptr,
    const int32_t* indices,
    const double* data,
    int row_start,
    int nrows,
    const float* l_full,
    int naux,
    float* wt_out,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t guga_unpack_row_jk_launch_stream(
    const uint64_t* row_jk,
    int nrows,
    int32_t* row_j,
    int32_t* row_k,
    cudaStream_t stream,
    int threads);

typedef struct Kernel25Profile {
  float count_ms;
  float prefix_sum_ms;
  float write_ms;
  float pack_ms;
  float sort_ms;
  float reduce_ms;
  float rle_ms;
  float indptr_ms;
  float unpack_ms;
  float sync_overhead_ms;
  int nnz_in;
  int nnz_out;
  int nrows;
  float bucket_ms;
  int bucket_counts[4];
} Kernel25Profile;

extern "C" void* guga_kernel25_workspace_create(int max_tasks, int max_nnz_in);
extern "C" void guga_kernel25_workspace_destroy(void* ws_handle);

extern "C" void guga_kernel25_workspace_get_bucket_info(
    void* ws_handle,
    int* bucketing_valid_out,
    int* bucket_offsets_out,
    int* bucket_counts_out,
    void** d_row_perm_out);

extern "C" void guga_kernel25_build_csr_from_jrs_allpairs_deterministic_inplace_device_ws(
    void* ws_handle,
    const int32_t* child,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    const int8_t* steps_table,
    const int32_t* nodes_table,
    int ncsf,
    int norb,
    int j_start,
    int j_count,
    int32_t* out_row_j,
    int32_t* out_row_k,
    int64_t* out_indptr,
    int32_t* out_indices,
    void* out_data,
    int out_data_type,
    int max_out,
    int* overflow_flag,
    cudaStream_t stream,
    int threads,
    int coalesce,
    int* out_nrows_host,
    int* out_nnz_host,
    int* out_nnz_in_host,
    int sync,
    int check_overflow_mode,
    int use_fused_count_write,
    Kernel25Profile* out_profile);

extern "C" void guga_kernel25_build_csr_from_tasks_deterministic_inplace_device_ws(
    void* ws_handle,
    const int32_t* child,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    const int8_t* steps_table,
    const int32_t* nodes_table,
    int ncsf,
    int norb,
    const int32_t* task_csf,
    const int32_t* task_p,
    const int32_t* task_q,
    int ntasks,
    int32_t* out_row_j,
    int32_t* out_row_k,
    int64_t* out_indptr,
    int32_t* out_indices,
    void* out_data,
    int out_data_type,
    int max_out,
    int* overflow_flag,
    cudaStream_t stream,
    int threads,
    int coalesce,
    int* out_nrows_host,
    int* out_nnz_host,
    int* out_nnz_in_host,
    int sync,
    int check_overflow);

// Fused hop kernel: single DFS walk fusing W-build + one-body + ERI contraction
template <int MAX_NORB_T, typename T>
void guga_fused_hop_launch_stream(
    const int32_t* child,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    const int8_t* steps_table,
    const int32_t* nodes_table,
    int ncsf,
    int norb,
    int j_start,
    int j_count,
    const T* x,
    const T* eri_mat,
    const T* h_eff_flat,
    T* y,
    int* overflow_flag,
    cudaStream_t stream);

// Phase-1-only fused hop: W-build + ERI contraction, writes G to g_out.
// Phase 2 scatter is handled externally via the EPQ table scatter kernel.
template <int MAX_NORB_T, typename T>
void guga_fused_hop_phase1_launch_stream(
    const int32_t* child,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    const int8_t* steps_table,
    const int32_t* nodes_table,
    int ncsf,
    int norb,
    int j_start,
    int j_count,
    const T* x,
    const T* eri_mat,
    const T* h_eff_flat,
    T* y,
    T* g_out,
    int* overflow_flag,
    cudaStream_t stream);

// Phase-1 + COO output fused hop: W-build + ERI contraction + COO connectivity.
// Phase 2 scatter is handled by guga_coo_scatter_launch_stream.
template <int MAX_NORB_T, typename T>
void guga_fused_hop_phase1_coo_launch_stream(
    const int32_t* child,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    const int8_t* steps_table,
    const int32_t* nodes_table,
    int ncsf,
    int norb,
    int j_start,
    int j_count,
    const T* x,
    const T* eri_mat,
    const T* h_eff_flat,
    T* y,
    T* g_out,
    int* overflow_flag,
    int* coo_nnz_counter,
    int32_t* coo_j_local,
    int32_t* coo_k,
    int16_t* coo_pq,
    T* coo_w2,
    int max_coo,
    cudaStream_t stream);

// Phase-1 + COO output fused hop (merged DFS variant, WP14):
// Groups pairs by (direction, start) and walks shared DRT prefix once per group.
template <int MAX_NORB_T, typename T>
void guga_fused_hop_phase1_coo_merged_launch_stream(
    const int32_t* child,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    const int8_t* steps_table,
    const int32_t* nodes_table,
    int ncsf,
    int norb,
    int j_start,
    int j_count,
    const T* x,
    const T* eri_mat,
    const T* h_eff_flat,
    T* y,
    T* g_out,
    int* overflow_flag,
    int* coo_nnz_counter,
    int32_t* coo_j_local,
    int32_t* coo_k,
    int16_t* coo_pq,
    T* coo_w2,
    int max_coo,
    cudaStream_t stream);

// COO scatter kernel: reads COO triples and scatters G into y.
template <typename T>
void guga_coo_scatter_launch_stream(
    const int32_t* coo_j_local,
    const int32_t* coo_k,
    const int16_t* coo_pq,
    const T* coo_w2,
    const T* g_tile,
    int nops,
    int nnz,
    T* y,
    cudaStream_t stream);

extern "C" void guga_triplet_apply_contracted_all_m_from_epq_table_launch_stream(
    const int16_t* node_twos,
    const int8_t* steps_table,
    const int32_t* nodes_table,
    int ncsf,
    int norb,
    const int64_t* epq_indptr,
    const int32_t* epq_indices,
    const int32_t* epq_pq,
    const double* x,
    const double* h_re,
    const double* h_im,
    const float* sixj_211,
    const float* t_factor,
    int twos_max,
    double* y_re,
    double* y_im,
    cudaStream_t stream,
    int threads);

extern "C" void guga_triplet_apply_contracted_all_m_dfs_launch_stream(
    const int32_t* child_bra,
    const int16_t* node_twos_bra,
    const int64_t* child_prefix_bra,
    int root_bra,
    int leaf_bra,
    int ncsf_bra,
    int twos_bra_total,
    const int16_t* node_twos_ket,
    const int8_t* steps_table_ket,
    const int32_t* nodes_table_ket,
    int ncsf_ket,
    int norb,
    int twos_ket_total,
    const double* x,
    const double* h_re,
    const double* h_im,
    const float* sixj_211,
    const float* t_factor,
    int twos_max,
    double* y_re,
    double* y_im,
    cudaStream_t stream,
    int threads);

extern "C" void guga_triplet_build_rho_all_m_from_epq_table_launch_stream(
    const int16_t* node_twos,
    const int8_t* steps_table,
    const int32_t* nodes_table,
    int ncsf,
    int norb,
    const int64_t* epq_indptr,
    const int32_t* epq_indices,
    const int32_t* epq_pq,
    const double* c_bra,
    int nb,
    const double* c_ket,
    int nk,
    const double* eta_re,
    const double* eta_im,
    const float* sixj_211,
    const float* t_factor,
    int twos_max,
    double* rho_re,
    double* rho_im,
    cudaStream_t stream,
    int threads);

extern "C" void guga_triplet_build_rho_all_m_dfs_launch_stream(
    const int32_t* child_bra,
    const int16_t* node_twos_bra,
    const int64_t* child_prefix_bra,
    int root_bra,
    int leaf_bra,
    int ncsf_bra,
    int twos_bra_total,
    const int16_t* node_twos_ket,
    const int8_t* steps_table_ket,
    const int32_t* nodes_table_ket,
    int ncsf_ket,
    int norb,
    int twos_ket_total,
    const double* c_bra,
    int nb,
    const double* c_ket,
    int nk,
    const double* eta_re,
    const double* eta_im,
    const float* sixj_211,
    const float* t_factor,
    int twos_max,
    double* rho_re,
    double* rho_im,
    cudaStream_t stream,
    int threads);

extern "C" void guga_triplet_build_gm_all_m_from_epq_table_launch_stream(
    const int16_t* node_twos,
    const int8_t* steps_table,
    const int32_t* nodes_table,
    int ncsf,
    int norb,
    const int64_t* epq_indptr,
    const int32_t* epq_indices,
    const int32_t* epq_pq,
    const double* c_bra,
    int nb,
    const double* c_ket,
    int nk,
    const double* h_re,
    const double* h_im,
    const float* sixj_211,
    const float* t_factor,
    int twos_max,
    double* gm_re,
    double* gm_im,
    cudaStream_t stream,
    int threads);

extern "C" void guga_triplet_build_gm_all_m_dfs_launch_stream(
    const int32_t* child_bra,
    const int16_t* node_twos_bra,
    const int64_t* child_prefix_bra,
    int root_bra,
    int leaf_bra,
    int ncsf_bra,
    int twos_bra_total,
    const int16_t* node_twos_ket,
    const int8_t* steps_table_ket,
    const int32_t* nodes_table_ket,
    int ncsf_ket,
    int norb,
    int twos_ket_total,
    const double* c_bra,
    int nb,
    const double* c_ket,
    int nk,
    const double* h_re,
    const double* h_im,
    const float* sixj_211,
    const float* t_factor,
    int twos_max,
    double* gm_re,
    double* gm_im,
    cudaStream_t stream,
    int threads);

// --------------------------------------------------------------------------
// Fused MRCI kernels (guga_cuda_kernels_mrci_fused.cuh)
// --------------------------------------------------------------------------

extern "C" void sym_pair_pack_launch_stream(
    const double* W, double* W_pair,
    const int32_t* pair_pq, const int32_t* pair_qp,
    int nrows, int nops, int npair,
    int64_t w_stride, int64_t wp_stride,
    cudaStream_t stream, int threads);

extern "C" void sym_pair_unpack_launch_stream(
    const double* G_pair, double* G,
    const int32_t* full_to_pair,
    int nrows, int nops, int npair,
    int64_t gp_stride, int64_t g_stride,
    cudaStream_t stream, int threads);

extern "C" void sym_pair_pack_f32_launch_stream(
    const float* W, float* W_pair,
    const int32_t* pair_pq, const int32_t* pair_qp,
    int nrows, int nops, int npair,
    int64_t w_stride, int64_t wp_stride,
    cudaStream_t stream, int threads);

extern "C" void sym_pair_unpack_f32_launch_stream(
    const float* G_pair, float* G,
    const int32_t* full_to_pair,
    int nrows, int nops, int npair,
    int64_t gp_stride, int64_t g_stride,
    cudaStream_t stream, int threads);

extern "C" void rdm12_reorder_delta_launch_stream(
    const double* dm1_pq, const double* gram0,
    double* dm1_out, double* dm2_out,
    int norb,
    cudaStream_t stream, int threads);

extern "C" void scatter_embed_batched_launch_stream(
    const double* x_sub, const int64_t* sub_to_full, double* x_full,
    int nsub, int nvec, int64_t sub_stride, int64_t full_stride,
    cudaStream_t stream, int threads);

extern "C" void gather_project_batched_launch_stream(
    const double* y_full, const int64_t* sub_to_full, double* y_sub,
    int nsub, int nvec, int64_t full_stride, int64_t sub_stride,
    cudaStream_t stream, int threads);

// P1A: Batched W-build + diagonal
extern "C" void build_w_from_epq_table_batched_launch_stream(
    const int64_t* epq_indptr, const int32_t* epq_indices,
    const int32_t* epq_pq, const double* epq_data,
    const double* x, int64_t x_stride,
    double* w_out, int64_t w_stride,
    int ncsf, int nops,
    int nvec, int v_start,
    int k_start, int k_count,
    cudaStream_t stream, int threads);

extern "C" void build_w_diag_batched_launch_stream(
    const int8_t* steps_table, const double* x, int64_t x_stride,
    double* w_out, int64_t w_stride,
    int ncsf, int norb,
    int j_start, int j_count,
    int nvec, int v_start,
    cudaStream_t stream, int threads);

// P5: RDM123 delta + symmetry
extern "C" void dm2_delta_correction_launch_stream(
    double* dm2, const double* dm1, int n,
    cudaStream_t stream, int threads);

extern "C" void dm2_4way_symmetry_launch_stream(
    const double* dm2_in, double* dm2_out, int n,
    cudaStream_t stream, int threads);

extern "C" void dm3_delta_correction_launch_stream(
    double* dm3, const double* dm2, const double* dm1, int n,
    cudaStream_t stream, int threads);

extern "C" void dm3_6way_symmetry_launch_stream(
    const double* dm3_in, double* dm3_out, int n,
    cudaStream_t stream, int threads);

// =============================================================================
// CIPSI frontier-hash (GPU selection/PT2 without materializing y[ncsf])
// =============================================================================

extern "C" void guga_apply_g_flat_scatter_atomic_frontier_hash_launch_stream(
    const int32_t* child,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    const int8_t* steps_table,
    const int32_t* nodes_table,
    int ncsf,
    int norb,
    const int32_t* task_csf,
    const double* task_scale,
    const double* task_g,
    int64_t g_stride,
    int ntasks,
    int32_t* hash_keys,
    double* hash_vals,
    int cap,
    int root,
    const uint8_t* selected_mask,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" void guga_apply_g_flat_scatter_atomic_frontier_hash_many_roots_launch_stream(
    const int32_t* child,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    const int8_t* steps_table,
    const int32_t* nodes_table,
    int ncsf,
    int norb,
    const int32_t* task_csf,
    const double* task_scale_task_major,
    int64_t task_scale_stride,
    int nroots,
    const double* task_g,
    int64_t g_stride,
    int ntasks,
    int32_t* hash_keys,
    double* hash_vals,
    int cap,
    const uint8_t* selected_mask,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t guga_cipsi_frontier_hash_clear_launch_stream(
    int32_t* keys,
    double* vals_root_major,
    int cap,
    int nroots,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t guga_cipsi_frontier_hash_extract_launch_stream(
    const int32_t* keys,
    const double* vals_root_major,
    int cap,
    int nroots,
    int32_t* out_idx,
    double* out_vals_root_major,
    int* out_nnz,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t guga_cipsi_score_and_select_topk_launch_stream(
    const int32_t* idx,
    const double* vals_root_major,
    int64_t vals_stride,
    int nnz,
    int nroots,
    const double* e_var,
    const double* hdiag,
    int ncsf,
    const uint8_t* selected_mask,
    double denom_floor,
    int max_add,
    int32_t* out_new_idx,
    int* out_new_n,
    double* out_pt2,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t guga_cipsi_score_and_select_topk_from_hash_slots_launch_stream(
    const int32_t* keys,
    const double* vals_root_major,
    int cap,
    int nroots,
    const double* e_var,
    const double* hdiag,
    int ncsf,
    const uint8_t* selected_mask,
    double denom_floor,
    int max_add,
    int32_t* out_new_idx,
    int* out_new_n,
    double* out_pt2,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t guga_cipsi_score_and_select_topk_from_hash_slots_v2_launch_stream(
    const int32_t* keys,
    const double* vals_root_major,
    int cap,
    int nroots,
    const double* e_var,
    const double* hdiag,
    int ncsf,
    const uint8_t* selected_mask,
    double denom_floor,
    int max_add,
    int32_t* out_new_idx,
    int* out_new_n,
    double* out_pt2,
    cudaStream_t stream,
    int threads);

// ---------------------------------------------------------------------------
// Heat-Bath SCI kernels
// ---------------------------------------------------------------------------

extern "C" cudaError_t guga_hb_screen_and_apply_launch_stream(
    const int32_t* sel_idx,
    const double*  c_root,
    int nsel,
    int root,
    const int8_t*  steps_table,
    const int32_t* nodes_table,
    int norb,
    int ncsf,
    const int32_t* h1_pq,
    const double*  h1_abs,
    const double*  h1_signed,
    int n_h1,
    const int64_t* pq_ptr,
    const int32_t* rs_idx,
    const double*  v_abs,
    const double*  v_signed,
    const double*  pq_max_v,
    double eps,
    const int32_t* child_table,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    int nnodes,
    int32_t* hash_keys,
    double*  hash_vals,
    int cap,
    const uint8_t* selected_mask,
    int* overflow_flag,
    cudaStream_t stream,
    int threads,
    const int8_t* sym_pq_allowed);

extern "C" cudaError_t guga_hb_screen_and_apply_many_roots_launch_stream(
    const int32_t* sel_idx,
    const double*  c_sel_row_major,
    int nsel,
    int nroots,
    const int8_t*  steps_table,
    const int32_t* nodes_table,
    int norb,
    int ncsf,
    const int32_t* h1_pq,
    const double*  h1_abs,
    const double*  h1_signed,
    int n_h1,
    const int64_t* pq_ptr,
    const int32_t* rs_idx,
    const double*  v_abs,
    const double*  v_signed,
    const double*  pq_max_v,
    double eps,
    const int32_t* child_table,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    int nnodes,
    int32_t* hash_keys,
    double*  hash_vals,
    int cap,
    const uint8_t* selected_mask,
    int* overflow_flag,
    cudaStream_t stream,
    int threads,
    const int8_t* sym_pq_allowed);

extern "C" cudaError_t cas36_diag_guess_candidates_u64_dense_launch_stream(
    const int32_t* child,
    const int64_t* child_prefix,
    uint64_t ncsf,
    int norb,
    const uint64_t* cand_idx_u64,
    int ncand,
    const double* h1_diag,
    const double* eri_ppqq,
    const double* eri_pqqp,
    int neleca,
    int nelecb,
    double* hdiag_out,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t cas36_cipsi_score_pt2_compact_u64_launch_stream(
    const uint64_t* idx_u64,
    const double* vals_root_major,
    int64_t vals_stride,
    int ncand,
    int nroots,
    const double* e_var,
    const double* cand_hdiag,
    const uint64_t* selected_idx_sorted_u64,
    int nselected,
    double denom_floor,
    uint64_t* score_bits_out,
    double* pt2_out,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t cas36_hb_screen_and_apply_u64_launch_stream(
    const uint64_t* sel_idx_u64,
    const double* c_root,
    int nsel,
    int root,
    int norb,
    uint64_t ncsf,
    const int32_t* h1_pq,
    const double* h1_abs,
    const double* h1_signed,
    int n_h1,
    const int64_t* pq_ptr,
    const int32_t* rs_idx,
    const double* v_abs,
    const double* v_signed,
    const double* pq_max_v,
    double eps,
    const int32_t* child_table,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    uint64_t* hash_keys,
    double* hash_vals,
    int cap,
    uint64_t label_lo,
    uint64_t label_hi,
    const uint64_t* selected_idx_sorted_u64,
    int nselected,
    int target_mode,
    int* overflow_flag,
    cudaStream_t stream,
    int threads,
    const int8_t* sym_pq_allowed);

extern "C" cudaError_t cas36_hb_screen_and_apply_many_roots_u64_launch_stream(
    const uint64_t* sel_idx_u64,
    const double* c_sel_row_major,
    int nsel,
    int nroots,
    int norb,
    uint64_t ncsf,
    const int32_t* h1_pq,
    const double* h1_abs,
    const double* h1_signed,
    int n_h1,
    const int64_t* pq_ptr,
    const int32_t* rs_idx,
    const double* v_abs,
    const double* v_signed,
    const double* pq_max_v,
    double eps,
    const int32_t* child_table,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    uint64_t* hash_keys,
    double* hash_vals_root_major,
    int cap,
    uint64_t label_lo,
    uint64_t label_hi,
    const uint64_t* selected_idx_sorted_u64,
    int nselected,
    int target_mode,
    int* overflow_flag,
    cudaStream_t stream,
    int threads,
    const int8_t* sym_pq_allowed);

extern "C" cudaError_t cas36_hb_emit_tuples_u64_launch_stream(
    const uint64_t* sel_idx_u64,
    const double* c_bound,
    int nsel,
    int norb,
    uint64_t ncsf,
    const int32_t* h1_pq,
    const double* h1_abs,
    const double* h1_signed,
    int n_h1,
    const int64_t* pq_ptr,
    const int32_t* rs_idx,
    const double* v_abs,
    const double* v_signed,
    const double* pq_max_v,
    double eps,
    const int32_t* child_table,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    uint64_t* out_keys,
    int* out_src,
    double* out_hij,
    int cap,
    uint64_t label_lo,
    uint64_t label_hi,
    const uint64_t* selected_idx_sorted_u64,
    int nselected,
    int target_mode,
    int* out_n,
    int* overflow_flag,
    cudaStream_t stream,
    int threads,
    const int8_t* sym_pq_allowed);

extern "C" cudaError_t cas36_exact_selected_emit_tuples_u64_launch_stream(
    const uint64_t* sel_idx_u64,
    const double* c_bound,
    int nsel,
    int norb,
    uint64_t ncsf,
    const int32_t* h1_pq,
    const double* h1_abs,
    const double* h1_signed,
    int n_h1,
    const int64_t* pq_ptr,
    const int32_t* rs_idx,
    const double* v_abs,
    const double* v_signed,
    const double* pq_max_v,
    const int32_t* child_table,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    uint64_t* out_keys,
    int* out_src,
    double* out_hij,
    int cap,
    const uint64_t* selected_idx_sorted_u64,
    int nselected,
    int* out_n,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t cas36_exact_selected_emit_tuples_dense_u64_launch_stream(
    const uint64_t* sel_idx_u64,
    const double* c_bound,
    int nsel,
    int norb,
    uint64_t ncsf,
    const double* h_base,
    const double* eri4,
    const int32_t* child_table,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    uint64_t* out_keys,
    int* out_src,
    double* out_hij,
    int cap,
    const uint64_t* membership_hash_keys,
    int membership_hash_cap,
    double* out_diag,
    int* out_n,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t cas36_exact_emit_rowhash_dense_u64_launch_stream(
    const uint64_t* sel_idx_u64,
    const double* c_bound,
    int nsel,
    int norb,
    uint64_t ncsf,
    const double* h_base,
    const double* eri4,
    const int32_t* child_table,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    uint64_t* row_hash_keys,
    double* row_hash_vals,
    int row_cap,
    uint64_t label_lo,
    uint64_t label_hi,
    const uint64_t* membership_hash_keys,
    int membership_hash_cap,
    int target_mode,
    double* out_diag,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t cas36_exact_external_apply_dense_many_roots_u64_launch_stream(
    const uint64_t* sel_idx_u64,
    const double* c_sel_row_major,
    int nsel,
    int nroots,
    int norb,
    uint64_t ncsf,
    const double* h_base,
    const double* eri4,
    const int32_t* child_table,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    uint64_t* hash_keys,
    double* hash_vals_root_major,
    int cap,
    uint64_t label_lo,
    uint64_t label_hi,
    const uint64_t* membership_hash_keys,
    int membership_hash_cap,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t cas36_sci_build_membership_hash_u64_launch_stream(
    const uint64_t* sorted_keys,
    int nkeys,
    uint64_t* hash_keys,
    int cap,
    cudaStream_t stream);

extern "C" cudaError_t cas36_sym_row_graph_spmm_launch_stream(
    const int64_t* row_ptr,
    const int32_t* col_idx,
    const double* hij,
    const double* diag,
    int nrows,
    const double* x,
    int64_t x_row_stride,
    int nvec,
    double* y,
    int64_t y_row_stride,
    cudaStream_t stream,
    int threads);

// ---------------------------------------------------------------------------
// Pair-wise H[i,j] evaluation kernels
// ---------------------------------------------------------------------------

extern "C" cudaError_t pairwise_materialize_u64_launch_stream(
    const uint64_t* sel_idx_u64,
    int nsel,
    int norb,
    uint64_t ncsf,
    const int32_t* child_table,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    int8_t*  steps_all,
    int32_t* nodes_all,
    int8_t*  occ_all,
    int16_t* b_all,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t pairwise_hij_u64_launch_stream(
    const uint64_t* sel_idx_u64,
    int nsel,
    int norb,
    uint64_t ncsf,
    const double* h_base,
    const double* eri4,
    const int32_t* child_table,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    const int8_t*  steps_all,
    const int32_t* nodes_all,
    const int8_t*  occ_all,
    const int16_t* b_all,
    double* H_out,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t pairwise_hij_bucketed_u64_launch_stream(
    const uint64_t* sel_idx_u64,
    int nsel,
    int norb,
    uint64_t ncsf,
    const double* h_base,
    const double* eri4,
    const int32_t* child_table,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    const int8_t*  steps_all,
    const int32_t* nodes_all,
    const int8_t*  occ_all,
    const int16_t* b_all,
    const uint64_t* occ_keys_sorted,
    const uint64_t* bucket_keys,
    const int32_t* bucket_starts,
    const int32_t* bucket_sizes,
    const int32_t* neighbor_offsets,
    const int32_t* neighbor_list,
    const int32_t* csf_to_bucket,
    const int32_t* target_offsets,
    const int32_t* target_list,
    const int32_t* target_offsets_1b,
    const int32_t* target_list_1b,
    int use_bucket_filter_phase2,
    double* H_out,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t cas36_exact_emit_tuples_dense_u64_launch_stream(
    const uint64_t* sel_idx_u64,
    const double* c_bound,
    int nsel,
    int norb,
    uint64_t ncsf,
    const double* h_base,
    const double* eri4,
    const int32_t* child_table,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    uint64_t* out_keys,
    int* out_src,
    double* out_hij,
    int cap,
    uint64_t label_lo,
    uint64_t label_hi,
    const uint64_t* membership_hash_keys,
    int membership_hash_cap,
    int target_mode,
    double* out_diag,
    int* out_n,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t pairwise_sigma_bucketed_u64_launch_stream(
    const uint64_t* sel_idx_u64,
    int nsel,
    int norb,
    uint64_t ncsf,
    const double* h_base,
    const double* eri4,
    const int32_t* child_table,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    const int8_t*  steps_all,
    const int32_t* nodes_all,
    const int8_t*  occ_all,
    const int16_t* b_all,
    const uint64_t* occ_keys_sorted,
    const int32_t* csf_to_bucket,
    const int32_t* target_offsets,
    const int32_t* target_list,
    const int32_t* target_offsets_1b,
    const int32_t* target_list_1b,
    const double* x,
    int nvec,
    double* y,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t pairwise_diag_bucketed_u64_launch_stream(
    const uint64_t* sel_idx_u64,
    int nsel,
    int norb,
    uint64_t ncsf,
    const double* h_base,
    const double* eri4,
    const int32_t* child_table,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    const int8_t*  steps_all,
    const int32_t* nodes_all,
    const int8_t*  occ_all,
    const int16_t* b_all,
    double* diag_out,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t pairwise_count_bucketed_u64_launch_stream(
    const uint64_t* sel_idx_u64,
    int nsel,
    int norb,
    uint64_t ncsf,
    const double* h_base,
    const double* eri4,
    const int32_t* child_table,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    const int8_t*  steps_all,
    const int32_t* nodes_all,
    const int8_t*  occ_all,
    const int16_t* b_all,
    const uint64_t* occ_keys_sorted,
    const uint64_t* bucket_keys,
    const int32_t* bucket_starts,
    const int32_t* bucket_sizes,
    const int32_t* neighbor_offsets,
    const int32_t* neighbor_list,
    const int32_t* csf_to_bucket,
    const int32_t* target_offsets,
    const int32_t* target_list,
    const int32_t* target_offsets_1b,
    const int32_t* target_list_1b,
    int table_cap,
    int32_t* workspace_keys,
    double* workspace_vals,
    int grid_blocks,
    int32_t* row_counts,
    double* diag_out,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t pairwise_fill_bucketed_u64_launch_stream(
    const uint64_t* sel_idx_u64,
    int nsel,
    int norb,
    uint64_t ncsf,
    const double* h_base,
    const double* eri4,
    const int32_t* child_table,
    const int16_t* node_twos,
    const int64_t* child_prefix,
    const int8_t*  steps_all,
    const int32_t* nodes_all,
    const int8_t*  occ_all,
    const int16_t* b_all,
    const uint64_t* occ_keys_sorted,
    const uint64_t* bucket_keys,
    const int32_t* bucket_starts,
    const int32_t* bucket_sizes,
    const int32_t* neighbor_offsets,
    const int32_t* neighbor_list,
    const int32_t* csf_to_bucket,
    const int32_t* target_offsets,
    const int32_t* target_list,
    const int32_t* target_offsets_1b,
    const int32_t* target_list_1b,
    int table_cap,
    int32_t* workspace_keys,
    double* workspace_vals,
    int grid_blocks,
    const int64_t* row_offsets,
    const int32_t* row_counts,
    int32_t* out_target_local,
    int32_t* out_src_pos,
    double* out_hij,
    double* diag_out,
    int* overflow_flag,
    cudaStream_t stream,
    int threads);

extern "C" cudaError_t pairwise_T_matrix_bucketed_u64_launch_stream(
    int nsel,
    int norb,
    const int32_t* child_table,
    const int16_t* node_twos,
    const int8_t*  steps_all,
    const int32_t* nodes_all,
    const int8_t*  occ_all,
    const int16_t* b_all,
    const int32_t* csf_to_bucket,
    const int32_t* target_offsets_1b,
    const int32_t* target_list_1b,
    const double*  ci_sel,
    double*        T_out,
    cudaStream_t stream,
    int threads);

#endif  // CUGUGU_GPU_GUGA_CUDA_KERNELS_API_H
