"""Explicit internal surface for solver decomposition helpers."""

from .cuda_policy import (
    apply_cuda_pool_hard_cap,
    apply_cuda_user_policy,
    auto_gpu_mem_hard_cap,
    cuda_budget_free_bytes,
    enforce_cuda_aggregate_offdiag_guard,
    enforce_cuda_fp32_large_cas_epq_policy,
    estimate_epq_peak_bytes,
    normalize_csr_host_cache_mode,
    normalize_cuda_accuracy_mode,
    normalize_cuda_user_policy_mode,
    normalize_matvec_cuda_path_mode,
    normalize_prefilter_trivial_tasks_mode,
    normalize_ws_cache_fraction,
    resolve_epq_overbudget_action,
    resolve_mixed_low_workspace_oom_fallback,
)
from .config import auto_num_threads
from .drt_cache import (
    DRTKey,
    ne_constraints_key_to_dict,
    ne_constraints_to_key,
    orbsym_to_tuple,
)
from .drt_runtime import drt_key, get_or_build_drt
from .matvec_runtime import (
    CUDA_MATVEC_BACKENDS,
    estimate_matvec_cuda_workspace_bytes,
    release_matvec_cuda_workspace,
    resolve_approx_cuda_frontend,
    resolve_matvec_cuda_ws_cache_budget_bytes,
    resolve_kernel_cuda_execution_mode,
    ws_needs_rebuild,
)
from .warm_state import (
    WARM_CUDA_MATVEC_BACKENDS,
    WARM_STATE_FORMAT_VERSION,
    normalize_warm_cas_metadata,
    warm_cas_metadata_from_jsonable,
    warm_cas_metadata_to_jsonable,
)
from .warm_state_runtime import (
    allowed_ci_devices_for_backend,
    load_warm_state,
    save_warm_state,
    update_warm_state,
    warm_state_ci0_if_compatible,
    warm_state_summary,
)

__all__ = [
    "WARM_CUDA_MATVEC_BACKENDS",
    "WARM_STATE_FORMAT_VERSION",
    "DRTKey",
    "apply_cuda_pool_hard_cap",
    "apply_cuda_user_policy",
    "auto_num_threads",
    "auto_gpu_mem_hard_cap",
    "cuda_budget_free_bytes",
    "allowed_ci_devices_for_backend",
    "drt_key",
    "CUDA_MATVEC_BACKENDS",
    "estimate_matvec_cuda_workspace_bytes",
    "get_or_build_drt",
    "enforce_cuda_aggregate_offdiag_guard",
    "enforce_cuda_fp32_large_cas_epq_policy",
    "estimate_epq_peak_bytes",
    "ne_constraints_key_to_dict",
    "ne_constraints_to_key",
    "normalize_csr_host_cache_mode",
    "normalize_cuda_accuracy_mode",
    "normalize_cuda_user_policy_mode",
    "normalize_matvec_cuda_path_mode",
    "normalize_prefilter_trivial_tasks_mode",
    "orbsym_to_tuple",
    "normalize_warm_cas_metadata",
    "normalize_ws_cache_fraction",
    "load_warm_state",
    "resolve_approx_cuda_frontend",
    "resolve_matvec_cuda_ws_cache_budget_bytes",
    "resolve_kernel_cuda_execution_mode",
    "release_matvec_cuda_workspace",
    "resolve_epq_overbudget_action",
    "resolve_mixed_low_workspace_oom_fallback",
    "save_warm_state",
    "update_warm_state",
    "warm_cas_metadata_from_jsonable",
    "warm_cas_metadata_to_jsonable",
    "warm_state_ci0_if_compatible",
    "warm_state_summary",
    "ws_needs_rebuild",
]
