from __future__ import annotations

from asuka.soc.si import (
    SOCIntegrals,
    SOCRASSIResult,
    SpinFreeState,
    SpinFreeStateInteractionResult,
    build_si_basis,
    build_si_hamiltonian_from_Gm,
    build_spinfree_state_interaction_matrices,
    compute_si_adjoint_weights,
    soc_state_interaction,
    soc_state_interaction_from_Gm,
    soc_state_interaction_rassi,
    soc_xyz_to_spherical,
    solve_spinfree_state_interaction,
    spinfree_state_interaction_from_states,
)
from asuka.soc.trdm import (
    apply_contracted_triplet_all_m,
    build_ci_rhs_soc_bra_term,
    build_ci_rhs_soc_full,
    build_rho_soc_m_streaming,
    trans_trdm1_triplet_all_streaming,
    trans_trdm1_triplet_streaming,
)
from asuka.soc.grad import (
    SOCCIZVectorResponse,
    SOCMultiSpinZVectorResponse,
    SOCSpinManifoldZVectorResponse,
    build_soc_ci_rhs_for_zvector,
    build_soc_orbital_gradient_matrix,
    build_soc_orbital_rhs_for_zvector,
    soc_lagrange_response_nuc_grad,
    soc_ao_to_mo,
    solve_soc_ci_zvector_response,
    solve_soc_ci_zvector_response_multi_spin,
    spinfree_states_from_mc,
)
from asuka.soc.triplet_op import apply_triplet_pq, rme_triplet_single_excitation, triplet_contribs_one
from asuka.soc.triplet_factors import (
    A_factor,
    Atilde_factor,
    B_factor,
    Btilde_factor,
    T_factor,
    phase_from_twos_sum,
)
from asuka.soc.wigner import (
    tri_delta,
    tri_delta_twos,
    wigner_3j,
    wigner_3j_twos,
    wigner_6j,
    wigner_6j_twos,
)
from asuka.soc.cuda_backend import (
    apply_contracted_triplet_all_m_cuda,
    build_triplet_factors_host,
    has_soc_cuda,
    make_triplet_factors_workspace_device,
)

__all__ = [
    "SOCIntegrals",
    "SOCRASSIResult",
    "SpinFreeState",
    "SpinFreeStateInteractionResult",
    "build_si_basis",
    "build_si_hamiltonian_from_Gm",
    "build_spinfree_state_interaction_matrices",
    "compute_si_adjoint_weights",
    "soc_state_interaction",
    "soc_state_interaction_from_Gm",
    "soc_state_interaction_rassi",
    "soc_xyz_to_spherical",
    "solve_spinfree_state_interaction",
    "spinfree_state_interaction_from_states",
    "apply_triplet_pq",
    "rme_triplet_single_excitation",
    "trans_trdm1_triplet_streaming",
    "trans_trdm1_triplet_all_streaming",
    "build_rho_soc_m_streaming",
    "apply_contracted_triplet_all_m",
    "build_ci_rhs_soc_bra_term",
    "build_ci_rhs_soc_full",
    "build_soc_ci_rhs_for_zvector",
    "soc_ao_to_mo",
    "build_soc_orbital_gradient_matrix",
    "build_soc_orbital_rhs_for_zvector",
    "soc_lagrange_response_nuc_grad",
    "solve_soc_ci_zvector_response",
    "solve_soc_ci_zvector_response_multi_spin",
    "SOCCIZVectorResponse",
    "SOCSpinManifoldZVectorResponse",
    "SOCMultiSpinZVectorResponse",
    "spinfree_states_from_mc",
    "triplet_contribs_one",
    "A_factor",
    "Atilde_factor",
    "B_factor",
    "Btilde_factor",
    "T_factor",
    "phase_from_twos_sum",
    "tri_delta",
    "tri_delta_twos",
    "wigner_3j",
    "wigner_3j_twos",
    "wigner_6j",
    "wigner_6j_twos",
    "has_soc_cuda",
    "build_triplet_factors_host",
    "make_triplet_factors_workspace_device",
    "apply_contracted_triplet_all_m_cuda",
]
